### ISSUE TITLE
希望可以新增的功能

### ISSUE THREAD

**Issue by HoeYeungHo** [RoderickQiu/wnr#10]
1. 白色背景有点刺眼 希望可以新增一个黑色的背景 这样子写东西也更方便
2. 希望可以增加白名单应用

**Comment by RoderickQiu** [comment]
目前已经支持适配系统暗黑模式，考虑在下一个版本中添加手动设置颜色配置的方式。
白名单在很长一段时间里不会被支持因为工作量太大。

**Comment by finhoo** [comment]
同希望增加黑色背景，此外，开始界面的菜单列表那些字体觉得太小了呀，看起来很费劲。

**Comment by finhoo** [comment]
> 目前已经支持适配系统暗黑模式，考虑在下一个版本中添加手动设置颜色配置的方式。
> 白名单在很长一段时间里不会被支持因为工作量太大。

同希望增加黑色背景，此外，开始界面的菜单列表那些字体觉得太小了呀，看起来很费劲。

**Comment by RoderickQiu** [comment]
> 
> 
> > 目前已经支持适配系统暗黑模式，考虑在下一个版本中添加手动设置颜色配置的方式。
> > 白名单在很长一段时间里不会被支持因为工作量太大。
> 
> 同希望增加黑色背景，此外，开始界面的菜单列表那些字体觉得太小了呀，看起来很费劲。

黑色背景已经可以在1.15.2版本中下拉菜单->设置->个性化设置->颜色模式，选择暗黑模式。

菜单列表将会在1.15.3或者1.16中再设计。
