### ISSUE TITLE
软件所有可以点击的部分如隐藏到托盘，最小化等，都可以拖出来一个快捷方式

### ISSUE THREAD

**Issue by PepsiiColaa** [RoderickQiu/wnr#100]
软件所有可以点击的部分如隐藏到托盘，最小化等，都可以拖出来一个快捷方式，类似于这样的
![image](https://github.com/RoderickQiu/wnr/assets/72384729/c56fab92-e78c-4ccf-b806-d1f914582df1)

**Comment by RoderickQiu** [comment]
对的，electron写出来好像就是这样，不大能改（）就他本质其实是js函数调用。

**Comment by PepsiiColaa** [comment]
收到！This is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by PepsiiColaa** [comment]
ok，thanks
