### ISSUE TITLE
主界面进度条方向改为从右向左，统一设计

### ISSUE THREAD

**Issue by luo-chuan** [RoderickQiu/wnr#101]
因为任务栏进度条，mini模式进度条的方向都是从右到左，所以希望主界面的进度条方向也是从右向左，保持一致的体验。
如图，目前是这样的：
![image](https://github.com/RoderickQiu/wnr/assets/33930736/d900962c-71d2-4eb6-a341-378d87aad69b)

**Comment by RoderickQiu** [comment]
改了。
