### ISSUE TITLE
希望丰富任务栏右键菜单

### ISSUE THREAD

**Issue by luo-chuan** [RoderickQiu/wnr#102]
托盘图标的右键菜单很丰富，而任务栏的右键菜单还没被开发，如果能优化就最好了。
![image](https://github.com/RoderickQiu/wnr/assets/33930736/f9a57ccd-c1c2-4ead-9d91-9eb24aa998bb)
这是目前的任务栏右键菜单：
![image](https://github.com/RoderickQiu/wnr/assets/33930736/1c650cfa-397b-4a8f-83ce-1a98fd0a085b)

**Comment by RoderickQiu** [comment]
任务栏菜单好像写起来不是很方便（）不知道现在electron相关api有没有优化过

**Comment by RoderickQiu** [comment]
https://www.electronjs.org/zh/docs/latest/tutorial/windows-taskbar windows没有给出友好的API，任务栏上的按钮只能是为启动一个新的进程提供参数，所以写起来麻烦，不大合适搞
