### ISSUE TITLE
误操作把工作模式设为了全屏

### ISSUE THREAD

**Issue by He469** [RoderickQiu/wnr#104]
我把工作模式设为了全屏，卸载软件重新安装后，打开还是全屏无法操作电脑，只能注销电脑强制退出，请问我该如何操作。

**Comment by RoderickQiu** [comment]
如果确实有需要，可以进入PE删除%AppData%/local/wnr。

**Comment by RoderickQiu** [comment]
一般来讲，如果是第一次打开一段非常长的全屏，应该会有退出选项。
