### ISSUE TITLE
“Show / Hide”於 Mini Mode 無效

### ISSUE THREAD

**Issue by GrimPixel** [RoderickQiu/wnr#106]
在 Mini Mode 單擊“Show / Hide”，其窗口不隠藏。

**Comment by RoderickQiu** [comment]
本来就是对主窗口的操作，隐藏/显示主窗口，但是minimode窗口不受影响，这恐怕才是大多数用户所想要的方式吧。你想隐藏mini mode窗口，手动把它关掉就行。
