### ISSUE TITLE
几点小建议

### ISSUE THREAD

**Issue by kuzen** [RoderickQiu/wnr#11]
1. portable版本形如虚设，解压到临时目录，关闭软件再删除。直接给zip版本就好了。
2. 安装版本不能自己选路径
3. 高分屏支持不好（我的是dpi：125%），菜单会模糊。
4. electron体积太大，能支持pwa或chrome插件吗

**Comment by RoderickQiu** [comment]
zip版本可以考虑。至于portable版本，其重要意义之一是在于配置文件都是放置在一起的。
安装版本将会在下一个版本中支持自选路径。
我的200%屏幕没问题，但好像确实125%时模糊……
如果不需要electron版本，你可以使用在线简化版：https://wnr-jr.scris.top/#/

**Comment by kuzen** [comment]
thanks

**Comment by RoderickQiu** [comment]
今天尝试修复125%缩放的问题，但似乎难以解决，网络上也没有什么相关的方案；认为是我所使用的Boostrap框架的问题，可能长期无法解决。
