### ISSUE TITLE
How to restart WNR to default?

### ISSUE THREAD

**Issue by Lpalencia86** [RoderickQiu/wnr#111]
First of all, thanks for the app, the utility and design are very helpful!

**The issue:** I set 1 hour of working and 10 minutes of rest with 4 loops.
I want to modify it but now I can't get into the settings because I turned off all skip and cancel options.
What can I do?

**Comment by RoderickQiu** [comment]
Delete `%APPDATA%/Roaming/wnr/timing-info.json` (it should be that, or the most similar one can quit unwanted timings.
