### ISSUE TITLE
`ctrl+q` quits the window unexpectedly

### ISSUE THREAD

**Issue by NeumoNeumo** [RoderickQiu/wnr#114]
I've customized my computer system and `ctrl+q` is a frequent hotkey on my laptop. Unfortunately, `ctrl+q` has a default behavior on `electron` to quit the program. Could you please unregister this hotkey?

**Comment by RoderickQiu** [comment]
Havent seen anybody who use this hotkey qwq. But you can tell me which version you use (linux, mac, win-installer, win-portable) and I may pack a version for you.

**Comment by NeumoNeumo** [comment]
> Havent seen anybody who use this hotkey qwq. But you can tell me which version you use (linux, mac, win-installer, win-portable) and I may pack a version for you.

I'm using linux. Thank you very much.

**Comment by NeumoNeumo** [comment]
Sorry, but it doesn't works. `ctrl+q` still quits `wnr`.

**Comment by RoderickQiu** [comment]
OK, let me find a solution later. Or you may clone it and try to fix, because also I've got a linux virtual machine, there is no developing environment in it.

**Comment by RoderickQiu** [comment]
Anyway, you may see if this works: https://drive.google.com/file/d/1ccVsg07MltuKQrZRlLajArL9xFXxxiyW/view?usp=sharing
It is actually hard for me to test linux, because it does not provide good support for arm64 sadly.
