### ISSUE TITLE
Long periods of time are not displayed correctly in the countdown mode's mini view.

### ISSUE THREAD

**Issue by Reunion31** [RoderickQiu/wnr#115]
This bug is relevant for this and the previous version. 

When I set a time longer than 60 minutes and then use the mini mode, the time is not displayed correctly. In this version it shows me "NaN m left." In the previous version, it used to show a jumble of numbers like "1.23.655....," but at least I could understand how much time was left. 

This is extremely inconvenient. Please fix the bug.

I'm Windows 10 and wnr x64 version.

![image](https://github.com/RoderickQiu/wnr/assets/72015211/c45dbb51-2c8d-4b98-b331-a797e7faa05e)

**Comment by RoderickQiu** [comment]
Oh, you're right. It is the case. Just that I seldom use long periods so didn't notice. Will fix asap.

**Comment by Reunion31** [comment]
I hope it's easy to fix. Can't wait for it:)

**Comment by RoderickQiu** [comment]
Sorry for the long delay. It is now fixed. Hoping to release a new version soon. Or you may simply download them here:
Installer: https://drive.google.com/file/d/1q4JRB8iOk6GNljpj4TkKyXO3Vpfuc4oQ/view?usp=sharing
Portable: https://drive.google.com/file/d/1NUHwV4i1pL-uZoK3nSeRAJAFeTwveYog/view?usp=sharing

**Comment by Reunion31** [comment]
Thanks a lot! I'll gladly wait for the github version too:D
