### ISSUE TITLE
Win11系统的迷你mini窗口没用了

### ISSUE THREAD

**Issue by Mantee0810** [RoderickQiu/wnr#116]
更新了win11
以前最爱的迷你窗口无法使用
点击迷你窗口按键后整个窗口消失
并且在右下角托盘只能通过“假装退出”来召唤
希望能修好QAQ

**Comment by Mantee0810** [comment]
对不起呀，我详细看了一下我还是在win10...
是纯粹的系统更新之后才出现的这个问题....

**Comment by Mantee0810** [comment]
修好了！滚回1.30.0的patch版本就可以了，感谢作者！！！

**Comment by RoderickQiu** [comment]
OK，没有问题就行。不过我没有发现你所说的这个问题qwq
