### ISSUE TITLE
点击退出按钮没有反应

### ISSUE THREAD

**Issue by tjx0722** [RoderickQiu/wnr#119]
![image](https://github.com/RoderickQiu/wnr/assets/42849881/307eb5fe-6659-4677-944e-1ad32a0a5159)
![image](https://github.com/RoderickQiu/wnr/assets/42849881/d89b8cdd-cfed-4c30-a5bf-4a9e704669c5)

**Comment by RoderickQiu** [comment]
你可能确实遇到了这个问题 但我确实没法复现 也不知道是哪里写出锅还是你的系统问题 总之对于这一个我几年前写的东西我也搞不懂问题出在哪里了qwq 但遇到这种情况建议使用任务管理器
