### ISSUE TITLE
小bug

### ISSUE THREAD

**Issue by finhoo** [RoderickQiu/wnr#12]
在“全屏专心休息”计时界面，正中间的小框并不是直接放大，而是先移到左上角停顿一两秒，再从左上角放大。（抱歉第一次在github上提建议，非专业相关，不知道自己描述的是否清楚）

**Comment by RoderickQiu** [comment]
感谢反馈；但这是我所使用的Electron框架在Windows上的固有问题，应该难以解决，在macOS上就应该是顺滑的。
