### ISSUE TITLE
番茄钟的时候能不能不显示强制弹出窗口

### ISSUE THREAD

**Issue by bertwill9470** [RoderickQiu/wnr#120]
只播放声音，弹出窗口可以只在显示在角落吗？能不能不要老是弹出然后影响做事，用户看到知道了听到声音不就达到效果了么

**Comment by RoderickQiu** [comment]
设置里可以设置吧。
<img width="364" alt="image" src="https://github.com/RoderickQiu/wnr/assets/42290260/29234544-b5d5-4b80-8360-75409632878d">
另外，你的语气好像你花钱买了一样，可惜没有。
