### ISSUE TITLE
建议重新修改一下单纯记时的功能

### ISSUE THREAD

**Issue by eamon2003** [RoderickQiu/wnr#122]
有的时候只是想单独计时 所以有一些建议
①设置中加入默认主页面为单纯计时，且加入单独的单纯计时默认时间（现在的默认时间是普通计时的休息时间）
②定时结束后不要弹出主页面 本来就已经会弹出一个结束框了 显得比较冗杂
此外还有些别的建议
例如把mini模式的阴影修改一下 现在这个阴影面积太大了 
![image](https://github.com/RoderickQiu/wnr/assets/51506762/1e195df7-2c64-47c4-98b1-905cb30ebe69)
软件很好用 其实我的需求时在我进行娱乐之前开一个倒计时 这样到点了就能提醒我 用手机的话一是比较割裂 不够直观 二是比较麻烦 也用了很多其他软件 但是感觉都不太好用 只有你这个目前最满足我的需求

**Comment by RoderickQiu** [comment]
关于设置默认主界面和不弹出主页面，设置里我记得都是有的，虽然当时写的不是很优雅就是了。你再找找看。
关于新feature，我懒得加了，这个项目现在事实上我已经懒得维护了。你可以自己提交pull request。
至于阴影，这个是使用系统接口的，我没有额外使得他变得更大。你可能得自行hack一下，看怎么把你的系统的窗口阴影做修改。

**Comment by eamon2003** [comment]
> 关于设置默认主界面和不弹出主页面，设置里我记得都是有的，虽然当时写的不是很优雅就是了。你再找找看。 关于新feature，我懒得加了，这个项目现在事实上我已经懒得维护了。你可以自己提交pull request。 至于阴影，这个是使用系统接口的，我没有额外使得他变得更大。你可能得自行hack一下，看怎么把你的系统的窗口阴影做修改。

我看到设置里有选项了 但是选了之后没效果 既然你不想维护了那就算了 请问哥在南方科大读研吗 我正准备考研 推荐考这里吗

**Comment by RoderickQiu** [comment]
哦。看来确实这么个bug。如果有bug的话我看着接下来有没有空修吧，但现在期末周事情很多，可能更新没有时效性的。

------

另外，其实我是本科生，哈哈。不过我现在也在Prof Yuxin Ma的team里做点事。我觉得南科大是好的，给钱和宿舍质量都在国内第一梯队吧。如果能找到自己喜欢方向的导师，是很好的地方。教授们发国外期刊会议都发很多的。不过就是公务员、选调之类可能会有点吃亏。然后今年开始南科大保护一志愿了，除了深理工联培以外不招调剂了。

**Comment by eamon2003** [comment]
> 哦。看来确实这么个bug。如果有bug的话我看着接下来有没有空修吧，但现在期末周事情很多，可能更新没有时效性的。
> 
> 另外，其实我是本科生，哈哈。不过我现在也在Prof Yuxin Ma的team里做点事。我觉得南科大是好的，给钱和宿舍质量都在国内第一梯队吧。如果能找到自己喜欢方向的导师，是很好的地方。教授们发国外期刊会议都发很多的。不过就是公务员、选调之类可能会有点吃亏。然后今年开始南科大保护一志愿了，除了深理工联培以外不招调剂了。

本科生啊 强的强的 那我慢慢等你修吧 那可以考虑报考你们学校了

**Comment by RoderickQiu** [comment]
> > 关于设置默认主界面和不弹出主页面，设置里我记得都是有的，虽然当时写的不是很优雅就是了。你再找找看。 关于新feature，我懒得加了，这个项目现在事实上我已经懒得维护了。你可以自己提交pull request。 至于阴影，这个是使用系统接口的，我没有额外使得他变得更大。你可能得自行hack一下，看怎么把你的系统的窗口阴影做修改。
> 
> 我看到设置里有选项了 但是选了之后没效果 既然你不想维护了那就算了 请问哥在南方科大读研吗 我正准备考研 推荐考这里吗

之前忘记这件事了，最近稍有些时间了哈哈。把这个修了。
