### ISSUE TITLE
发现安卓上没有wnr这么好的软件，能否做个安卓版本

### ISSUE THREAD

**Issue by xiaoxin6182** [RoderickQiu/wnr#123]
发现安卓上（平板电脑）没有wnr这么好的软件，能否做个安卓版本，特别适合小朋友，小朋友玩起来根本不管时间，如果有个安卓版本那就好了。其它安卓上时间限制的软件也测试了很多，但是都没有wnr好。。。。如果能做的像win版本一样好，其实也可以收费的。

平板电脑很重要，很多小朋友学习都是在平板电脑，假如以后做的话，希望对平板着重优化。。。。

**Comment by RoderickQiu** [comment]
您好，我目前事情比较多 可能无法腾出时间开发安卓版本。我推荐一个安卓上的软件：不做手机控，可以去看看。如果权限都给了可以实现高强度锁机。
