### ISSUE TITLE
状态切换的时候自动弹出窗口，但是时间卡住不动

### ISSUE THREAD

**Issue by WangZichen99** [RoderickQiu/wnr#124]
工作切换到休息或者休息切换到工作的时候自动弹出窗口，但是时间不变，点什么都没用，必须要在任务栏右键点一下显示/隐藏，时间才会更新，这是怎么回事，win10操作系统
![image](https://github.com/user-attachments/assets/3efa63ca-b560-4b17-bfc1-b7144e6d2d7e)

**Comment by WangZichen99** [comment]
补充：隐藏至托盘菜单会这样，最小化至任务栏不会

**Comment by RoderickQiu** [comment]
我尝试了多种方式，但是没发复现你所说的情况。当然我用的是win11。
<img width="377" alt="image" src="https://github.com/user-attachments/assets/e429f796-aea2-4c49-96b5-28bfb7cbc253">
不过你可以尝试修改这里的设置试试，或者就使用能用的最小化和mini模式。

**Comment by WangZichen99** [comment]
这两个配置都是通知且不弹出，配置应该是对的，不知道是什么原因导致的。神奇的是昨天这个应用一直也没有提示我该休息了，也就是说如果我不去管它，它就一直不会提示任何信息（应该也是卡住了），我试了最小化和隐藏都是这样，难道是我工作的笔记本太垃圾了。。。
![image](https://github.com/user-attachments/assets/538fd716-e086-4d5d-825a-226020f90d0a)

**Comment by WangZichen99** [comment]
今天又好了，就这样吧

**Comment by RoderickQiu** [comment]
通知那个，是不是开了勿扰模式啥的hhhh。因为通知走的是系统通知api，如果开了勿扰而且没有允许接着发通知，那确实就没有显示了。或者你就不使用通知且不弹出，使用别的什么模式？
