### ISSUE TITLE
弹窗提醒时，任务栏上无关应用也会高亮

### ISSUE THREAD

**Issue by gitusr-2021** [RoderickQiu/wnr#126]
番茄钟结束时，弹窗提醒，任务栏上wnr会高亮，同时无关应用也会高亮
![image](https://github.com/user-attachments/assets/4a832dcd-538e-4326-a1e9-557d447ac1ce)

**Comment by RoderickQiu** [comment]
抱歉之前没有回复。但是我似乎无法复现你的情况？请问你的情况是经常出现吗？会在怎么样的具体情形中出现？你的wnr版本是什么？等等。如果不影响使用也可以先就这样？hhhh

**Comment by gitusr-2021** [comment]
经常会出现。具体如第一个视频演示，edge打开时打开wnr进行计时，后面最小化了wnr和edge，计时结束时弹窗，wnr和edge都高亮了。第二个视频，在桌面打开wnr再最小化，弹窗时就只有wnr高亮。wnr版本是1.30.2，1.30.1也会出现。win11和win10都会出现。倒也没有影响wnr的使用，但有时wnr弹窗把微信也给高亮了，就会误导我以为微信有新消息。也不算很大的问题hhh

https://github.com/user-attachments/assets/58a23923-e743-4436-a2ee-ec1d87783e10

https://github.com/user-attachments/assets/cf55b888-8def-49a8-80f6-28c54b1c9f72

**Comment by RoderickQiu** [comment]
我确实搞不清楚hhh。不过我直接把相关的api都关了，然后可以考虑为你生成一个弹窗时直接不闪烁的版本。你是用的是什么系统？默认会给你一份nsis installer+64位的。

**Comment by gitusr-2021** [comment]
我用Windows10和Windows11，谢谢大佬！

**Comment by RoderickQiu** [comment]
链接: https://pan.baidu.com/s/1Ckt-mW9SnAswffXeaXmV8w?pwd=wyqk 提取码: wyqk 复制这段内容后打开百度网盘手机App，操作更方便哦 你可以测试一下？

**Comment by gitusr-2021** [comment]
wnr不闪烁，但是最小化的另一个应用还是闪烁。这个也不影响wnr的使用，就这样吧，也不占用大佬宝贵的精力了

https://github.com/user-attachments/assets/71fcf06f-51f7-40c2-bf9a-7b79b5b97a20

**Comment by RoderickQiu** [comment]
好的 不好意思但这确实很奇怪了qwq……当然也可能会不会是win11的bug了？hhhh

**Comment by gitusr-2021** [comment]
win10和win11都有，不排除是windows或者yarn的bug？hhh
