### ISSUE TITLE
没有fedora版本

### ISSUE THREAD

**Issue by gwl7810** [RoderickQiu/wnr#13]
没有fedora版本

**Comment by RoderickQiu** [comment]
我个人不使用Linux，而每个平台都需要经过适配。因此暂时没有计划适配Fedora。
如果你愿意自己Fork一个分支并且向我贡献Fedora适配、Linux适配，我将很感激。

**Comment by RoderickQiu** [comment]
这个issue已经被打开很久了，想要了解一下目前您是否可以在Linux上运行wnr？
（应该可以运行，不过其实在`main.js`中我使用了一些可能在linux下无效的API「可能需要参考electron官方文档了」和一些可能不那么严谨的`process.platform`判定「其中多数应该是严谨的」，导致部分功能可能显得buggy）
