### ISSUE TITLE
希望去掉各种windows弹窗确认按钮提示信息

### ISSUE THREAD

**Issue by zhepama** [RoderickQiu/wnr#16]
1.  看起来LOWB

2.  使用习惯上毫无必要,每次都要确认下.烦

3.  开始和结束时,声音一直响直到点了,确认按钮..

**Comment by RoderickQiu** [comment]
之所以添加提示的原因是不确认直接继续可能会导致提示被用户忽略。
“全局设置”中“时间结束后确认框显示设置”可以解决你的问题。
