### ISSUE TITLE
时间统计模块

### ISSUE THREAD

**Issue by PeiOrange888** [RoderickQiu/wnr#17]
希望能开发不同类型的时间统计模块，这样可以直观了解自己的学习时间和效率

**Comment by RoderickQiu** [comment]
已经添加入计划列表，将会添加在下一个大版本（1.17）中。
谢谢反馈。

**Comment by RoderickQiu** [comment]
@PeiOrange888 目前已经开始设计时间统计模块，如果你可以清晰描述一下你的需求，我可能可以作出一个更加完善的统计功能来。你也可以发邮件到scrisqiu@hotmail.com。

**Comment by RoderickQiu** [comment]
已经加入v1.17.0。
