### ISSUE TITLE
关于MINI模式

### ISSUE THREAD

**Issue by gloriohust** [RoderickQiu/wnr#18]
很喜欢这个模式，既不占用任务栏图标，又能即时看到当前周期的剩余时间。但是目前版本的wnr中，如果我已经设置为MINI模式了，经过一组“工作+休息”后，又会自动从MINI模式中退出来，需要我重新再设置MINI模式。
希望对此予以改进，使得我设置完MINI模式之后，下一组“工作+休息”开始时能默认维持在MINI模式，直到我手动退出MINI模式。

**Comment by RoderickQiu** [comment]
好的，已经添加进计划列表，最近比较忙，应该会在下周末解决这一问题。
谢谢反馈！

**Comment by RoderickQiu** [comment]
今天原本的任务取消了，于是有时间做了一下这一功能，稍后应该就会发1.16.1版本。
