### ISSUE TITLE
Does not run on Mac 10.14.3

### ISSUE THREAD

**Issue by chilton** [RoderickQiu/wnr#2]
Launches and crashes. Says I should check with the developer.

**Comment by RoderickQiu** [comment]
I will soon try to check.
Could you please send me a screenshot?

**Comment by RoderickQiu** [comment]
Well, I re-install my program and this problem truly occured. I have scheduled to have an update soon, so this problem should be solved.

**Comment by RoderickQiu** [comment]
@chilton Now a new version has been released. 
You can now test it. I've tested on my 10.14.5 and it was OK.
Any more talks and issues are greatly appreciated!

**Comment by RoderickQiu** [comment]
Hope the problem has been solved.
