### ISSUE TITLE
鼠标左侧按键可以退出全屏专心

### ISSUE THREAD

**Issue by SamHou2007** [RoderickQiu/wnr#20]
当我按下鼠标左侧的按键（相当于在浏览器中按下返回键），wnr返回到了主菜单，这样起不到全屏专心的效果
如图：
![UUejFs.jpg](https://s1.ax1x.com/2020/07/14/UUejFs.jpg)

**Comment by RoderickQiu** [comment]
我不用鼠标，也没有用过有这个功能的鼠标。过一段时间研究一下。

**Comment by RoderickQiu** [comment]
请问在v1.17.0中是否解决了？

**Comment by SamHou2007** [comment]
解决了，感谢
