### ISSUE TITLE
更新很麻烦

### ISSUE THREAD

**Issue by zhepama** [RoderickQiu/wnr#21]
现在更新每次都来github下载
可以做个scoop这样的源..

**Comment by RoderickQiu** [comment]
没有用过scoop，请问它在中国区速度如何？
添加到choco、scoop、homebrew这样的源其实是可以考虑的，过段时间了解一下。
此外，这倒是启发了我一点：可能会在下个版本中实现在应用内直接查看更新日志。

**Comment by zhepama** [comment]
他的下载的地址仍然可以是github的release压缩包
所以速度主要看提供的地址

**Comment by RoderickQiu** [comment]
那可能不会加入，因为我也没有服务器，如果跑github release的话太慢了，不适合一个60mb的程序。
如果提出这个issue是觉得github不够快的话，我下次国内用户就直接转gitee吧。

**Comment by kidonng** [comment]
虽然这个 issue 已经关了，但是我还是打扰一下各位吧。我已经将 wnr 添加到了我的个人 bucket （https://github.com/kidonng/sushi），有需要的可以使用。

另外关于目前 wnr 在 Windows 平台的打包有个问题想询问 @RoderickQiu。目前有四个版本：

- 32 位安装包
- 64 位安装包
- 64 位安装包（便携版）
- 64 位压缩包

前两个是没有问题的，但是后两个在架构和格式上与通常的做法不太一样。这里以 https://github.com/yang991178/fluent-reader 为参照，后两个最好是：

- 32 位压缩包（便携版）
- 64 位压缩包（便携版）

**Comment by RoderickQiu** [comment]
@kidonng 感谢关注。接下来可能会把压缩包方式改为真正储存文件便携的然后删去当前的Portable版本（基于NSIS打包的单文件可执行形式，其实有一定性能问题）。

**Comment by RoderickQiu** [comment]
@kidonng 按照需求更新了v1.17.1-patch版本：https://github.com/RoderickQiu/wnr/releases/tag/v1.17.1-patch。可以再同步到Scoop了。

另外，想要问一下，每次更新后，是否需要通知你进行同步？如果需要，麻烦留一下你的邮箱。（不过你如果本人就是wnr的用户，在应用里面就会收到更新提示了。）

**Comment by zhepama** [comment]
@RoderickQiu 
不用通知他做同步的..
scoop的仓库的脚本,使用github的actions每天会自动查找更新版本,以及下载地址的

**Comment by kidonng** [comment]
@RoderickQiu 不用劳烦您通知，会自动更新。
