### ISSUE TITLE
[功能建议] 在桌面显示计时器, 显示的计时器可以设置为鼠标穿透, 不影响操作其他程序, 参考yapa2

### ISSUE THREAD

**Issue by zhoujin7** [RoderickQiu/wnr#22]
[功能建议] 在桌面显示计时器, 显示的计时器可以设置为鼠标穿透, 不影响操作其他程序, 参考yapa2
![image](https://user-images.githubusercontent.com/8288988/90370239-b045ae80-e09f-11ea-85d1-40829bd3e919.png)
![image](https://user-images.githubusercontent.com/8288988/90370470-0a467400-e0a0-11ea-835d-a8ad8150c541.png)
**鼠标可穿透**, 不影响操作其他程序.
https://github.com/YetAnotherPomodoroApp/YAPA-2
加上这个功能, 是不是就非常完美了.

**Comment by RoderickQiu** [comment]
看上去不错。对mini模式的鼠标穿透可选项会在下一个版本添加。

**Comment by RoderickQiu** [comment]
抱歉，但Electron框架提供的相关鼠标可穿透API只能用Buggy来形容，目前在Electron社区中似乎也并没有一个完美的方案（只有一些不能保障兼容性的Hacky方案，其中多数根本在Win10上无效），因此可能暂时不会添加可穿透模式。

事实上，体验了一下YAPA2，结论是它的Unclickable功能似乎在我的Win 10 v2004上也是无效的…（不过网易云的歌词显示是能够正常实施穿透的，但那好象是基于Qt的实现，对于Electron应用参考价值就不大了）。

会持续追踪相关最新进展，未来某个时间点会添加这一功能。
