### ISSUE TITLE
[小问题]为什么会在开始菜单中自动添加SnoreToast文件夹/快捷方式

### ISSUE THREAD

**Issue by zhoujin7** [RoderickQiu/wnr#23]
[小问题]为什么会在开始菜单中自动添加SnoreToast文件夹/快捷方式, 是否有办法禁止生成它, 或者自动删除.
windows 10

**Comment by RoderickQiu** [comment]
在Windows10上，没有注册开始菜单项目的程序不能发送通知；因此为Windows上便携版基于node-notifier类库通过SnoreToast发送通知（是KDE开发的安全开源项目），为了开发方便，在Windows安装版和macOS上也使用了相同的方案。
