### ISSUE TITLE
Unreadable font color in intro

### ISSUE THREAD

**Issue by Raduan77** [RoderickQiu/wnr#24]
Hey there. I find it very hard to read text with such font color in your app's intro.
- Platform: macOS Catalina 10.15.6
- Dark theme: Turned on.

Adding the screenshot for more details.
![image](https://user-images.githubusercontent.com/36044389/90425861-201c5f00-e0c9-11ea-99ca-d2348bf99866.png)

**Comment by RoderickQiu** [comment]
Kind of. Will fix in next release. Thanks.
