### ISSUE TITLE
Upgrade to electron 12 as it is way faster and works better too

### ISSUE THREAD

**Issue by fisforfaheem** [RoderickQiu/wnr#29]
it would mean a lot

**Comment by RoderickQiu** [comment]
Not interested in upgrading to v12 yet, because it's still in beta progress.
We will only follow a new version of electron when it has long been stable.
However, we'll keep on noticing what's going on about v12.
Thanks for suggesting.

**Comment by fisforfaheem** [comment]
what about version 11? it's way stable er
