### ISSUE TITLE
功能改进建议

### ISSUE THREAD

**Issue by zwb124** [RoderickQiu/wnr#3]
Mac下没法隐藏app？能否只在状态栏显示，另外可以尝试支持touchbar上显示

**Comment by RoderickQiu** [comment]
好的；会增加从dock隐藏的功能（这是你的想法吧？）

另外 因为我的电脑没有touchbar 我会尝试使用 https://github.com/sindresorhus/touch-bar-simulator 在未来某个时间点进行开发 不一定是最近 当然，如果你想把touchbar设置你想要的样子 欢迎开pull request
（相关API：https://www.electronjs.org/docs/api/touch-bar）

当两个功能都完成后，此issue才会被关闭。

**Comment by zwb124** [comment]
有没有touchbar无所谓，不过彻底隐藏还是有用的，因为一旦运行其实很少会打开它，让它在菜单栏里有个图标就够了。感谢采纳我的建议。

另外我问一句，如果一个时钟到时间了，然后屏幕被全屏锁定了，按什么键能在不到时的情况下退出这个锁定？

**Comment by RoderickQiu** [comment]
目前的设置是你不能退出（我特意花了好多时间让你其实无法退出），这和我制作这款软件的初衷有关（科学作息，包括强制让自己离开电脑休息）。你如果不想要这样的设计，目前的办法是不开启全屏专心模式，而是使用普通模式。
或者说你是否认为把全屏和全屏专心模式分开（既：提供全屏不专心模式，可以退出）会更好？但我认为这样做的问题是在于可能起不到让你离开电脑的效果。

取决于你使用wnr的需求了。（可以提供吗）

**Comment by zwb124** [comment]
哦，我没注意切换模式，那现在这样挺好的，别改了，我觉得很合理

**Comment by zwb124** [comment]
找了一堆关于番茄钟的程序，最后就觉得你这个最好，简洁，没有那么多乱七八糟的东西，感觉appstore里的很多应用都太复杂了，把简单事情复杂化了，用着很不舒服，支持你的程序，如果有机会会推荐给同事用

**Comment by RoderickQiu** [comment]
谢谢！一直是因为自己在用才在维护（一直没有怎么推广，过段时间会考虑进行），有了你这样的支持者，将会吸引我更加努力维护：D
------
刚才发现最新的版本有一个问题，系统级暗黑模式下checkbox显示似乎不正常，会在下一版本中一并修改。

**Comment by RoderickQiu** [comment]
你应该已经体验过wnr的从dock隐藏的功能了（从设置里选中此项目）。
然后今天我闲着没事做 就顺手下了个touchbar simulator，然后写了个touchbar适配。将会在近期推出v1.14.0的时候一并发布。

**Comment by RoderickQiu** [comment]
感谢关注 如果没有别的问题的话 此issue就可以被关闭了
如果有想法可以随时再reopen
：D
