### ISSUE TITLE
Task Checklist and long breaks(feature request)

### ISSUE THREAD

**Issue by ToTheMoon1234** [RoderickQiu/wnr#31]
I'm having a good time using the app especially the full screen mode. I would like to make a few suggestions that I think will benefit all it's users.

**Task Checklist**
It would be a nice feature to have a checklist in which I can write my tasks for the day and mark a task as done when it is finished. It will help me focus better if I see a checklist front of me with the timer.

**Long Breaks and Special Breaks**
Along with the short breaks, a feature to take a long break after 3-4 short breaks and also initiate special breaks like having food or going for a walk whenever a user wants(use limited to a numbers of time). It will help to plan all the sessions in the morning so that I know the number of sessions I'm having and also not close timer whenever I need the special breaks.

**Ability to pause the timer only during breaks**
Sometimes I need to discuss certain work and study related stuff with my friends during the break and a lot of times the conversation goes beyond the break time limit. A option to pause the timer during break session only would help a lot otherwise I have to cut the conversation short as the timer begins again. I only want the ability to pause the break timer during the break session only and not during the work timer session as otherwise I find myself pausing the timer in a work session often which results in loss of focus. An option to extend the break session will work just as well.

I'm enjoying using this wonderful app and I'm sure these features would make it even better for everyone. Thanks!

**Comment by RoderickQiu** [comment]
I think your suggestions are quite reasonable and I think I will made most of them into wnr later (as I'm considering a big update too!) Things like special breaks and ability to pause only during breaks will surely be implemented in the big update waiting to be finished in my Spring Festival vacation.

Thanks for suggesting.

**Comment by RoderickQiu** [comment]
However, the task checklist feature will still be considered whether or not to make it into wnr.
Reason: there has already been quite much of awesome tasklist apps and I'm hesitating whether it worths to make a new solution for it.

**Comment by ToTheMoon1234** [comment]
Thank You so much!

**Comment by ToTheMoon1234** [comment]
> However, the task checklist feature will still be considered whether or not to make it into wnr.
> Reason: there has already been quite much of awesome tasklist apps and I'm hesitating whether it worths to make a new solution for it.

Yes but the problem is while on fullscreen mode I am not able to see the tasklist app. But even if it not made into a feature I can always use other checklist app during the break so I think you can skip this feature if you want.

**Comment by RoderickQiu** [comment]
> > However, the task checklist feature will still be considered whether or not to make it into wnr.
> > Reason: there has already been quite much of awesome tasklist apps and I'm hesitating whether it worths to make a new solution for it.
> 
> Yes but the problem is while on fullscreen mode I am not able to see the tasklist app. But even if it not made into a feature I can always use other checklist app during the break so I think you can skip this feature if you want.

I will surely consider about it later but I can't say for sure that it will be added. Currently you can type down what you are going to do in the [More Items -> Notes] in the index page of the software.

**Comment by RoderickQiu** [comment]
Looking back, I think by v1.23.0, wnr has got something related to the tasklist feature (although not a full-function tasklist but only title and notes that can be modified).
But it was a pity that the promised big update reconstructing the whole timer system which can make it easy to implement a special break feature wasn't made, because I has been constantly lack of enough time and willingness to do it (as a student, I don't think I'll be freer the next year..).
But with modifiable title/notes and pause timer only when working implemented, I think I'm now confident enough to close this issue.
#45 can be dealt with soon I think, because it wasn't something big but something smaller.

**Comment by ToTheMoon1234** [comment]
As a busy student myself, I understand your situation. Thanks for implementing the new features, it is the best timer app I have used. I hope for the best for your future!
