### ISSUE TITLE
计时统计问题

### ISSUE THREAD

**Issue by 1198560751** [RoderickQiu/wnr#32]
通过测试 计时暂停也会增加 计时统计时长 ？？？ 这个问题是否可以修复?

**Comment by RoderickQiu** [comment]
should because changes in timing logic
will fix later

**Comment by RoderickQiu** [comment]
新版本即将发布，解决了这一问题。

**Comment by RoderickQiu** [comment]
之前遇到了问题发布延迟了，现在应该可以下载v1.21.1了。

**Comment by 1198560751** [comment]
测试，工作计时进行暂停，
![image](https://user-images.githubusercontent.com/57899844/106411496-651e2d00-6480-11eb-8bdc-77f0d45dad56.png)
使用统计时间还是会增加
![image](https://user-images.githubusercontent.com/57899844/106411545-7ff0a180-6480-11eb-8e32-8bc1df33ef3c.png)

**Comment by RoderickQiu** [comment]
我测试了一下，没有遇到问题。你可以再检查一下，或者问题不严重就算了吧，或者详细地录屏一下让我能更清楚地了解实况。

**Comment by 1198560751** [comment]
工作计时进行暂停，使用统计时间还是会增加。就是说，在工作计时的时候选择暂停，统计中工作时间会一直随着暂停的时间增加而增加

**Comment by RoderickQiu** [comment]
按你说的做了，但我在我这里真的无法复现。你要不重新下一遍1.21.1试试？

**Comment by 1198560751** [comment]
我重新下了一遍1.21.1，统计时间那里还是会把暂停的时间加进去

**Comment by RoderickQiu** [comment]
我懂了，你是暂停之后直接退出了，我之前测试都是先继续计时的。
懒得为这个发新版本了，你告知一下你用的是Win还是Mac，64位还是32位，便携版还是安装版，我给你专门打个包吧。

**Comment by 1198560751** [comment]
> 我懂了，你是暂停之后直接退出了，我之前测试都是先继续计时的。
> 懒得为这个发新版本了，你告知一下你用的是Win还是Mac，64位还是32位，便携版还是安装版，我给你专门打个包吧。

哦哦，我用的是Win的64位，便携版。我暂停了计时没有点×退出，我就放在那里，然后统计模块那里显示的时间是增加的，我虽然把计时暂停了，统计时间还是会增加，也就是会把暂停的时间增加上去，我觉得这个统计时间不能把暂停的时间也加进去

**Comment by 1198560751** [comment]
> > 我懂了，你是暂停之后直接退出了，我之前测试都是先继续计时的。
> > 懒得为这个发新版本了，你告知一下你用的是Win还是Mac，64位还是32位，便携版还是安装版，我给你专门打个包吧。
> 
> 哦哦，我用的是Win的64位，便携版。我暂停了计时没有点×退出，我就放在那里，然后统计模块那里显示的时间是增加的，我虽然把计时暂停了，统计时间还是会增加，也就是会把暂停的时长增加上去，我觉得这个统计时间不能把暂停的时长也加进去

**Comment by RoderickQiu** [comment]
https://scris.lanzous.com/i8zm3l9ojkd
给你吧，你看能不能用。

**Comment by 1198560751** [comment]
哦哦，这个可以的
