### ISSUE TITLE
统计事项是否能够生成时间轴？

### ISSUE THREAD

**Issue by adxrgh** [RoderickQiu/wnr#37]
统计事项现在太简单，只有一个时间的加总，如果能够有具体的时间轴，就可以加到手帐里面来，具体检查自己的时间安排。

**Comment by RoderickQiu** [comment]
简单来讲，这是个大工程，但我目前重心放在另外一个项目上，所以只提供小更新和错误修复（换言之，我半年内都不会做这个）。如果你很需要，请自行添加任务内容到手账里，或者你可以选择给项目贡献代码，有任何疑问可以问我。
