### ISSUE TITLE
mini模式win10拖动按键到桌面会生成空的快捷方式

### ISSUE THREAD

**Issue by LRTFK** [RoderickQiu/wnr#39]
mini模式win10拖动按键到桌面会生成空的快捷方式，win10 20h2，
mini模式之后拖动暂停按键到桌面会生成stopper()的快捷方式
恢复正常窗口的按钮拖动到桌面会成成recover()的快捷方式
左按钮backer()，右按钮skipper()等等
这些快捷方式的链接都类似 javascript:stopper()

**Comment by RoderickQiu** [comment]
这好像是所使用的electron框架的固有缺陷，我好像也找不到很好的解决办法。
