### ISSUE TITLE
weird acceptable range of loop times

### ISSUE THREAD

**Issue by NKID00** [RoderickQiu/wnr#40]
## How to reproduce
1. Open wnr.
2. Set the values to loop for 1.7 times.
3. The timing functionality still works with some weird interesting behaviors (e. g. looping count keeps increasing at every second forever and ever). Neither error nor warning was given.

In the case of looping for 0 times, wnr will never stop looping, like the infinity mode. Is it a feature?

**Comment by RoderickQiu** [comment]
yeah it is a problem that it malfunctions (although I cannot have it increasing?)
and the inifinity mode _is_ a feature and you can officially enables it through settings
thanks for digging this old bug out
and you can really read jquery-mixed html!
