### ISSUE TITLE
weird "all together" information when specific time intervals (<= 1 or float point) are given

### ISSUE THREAD

**Issue by NKID00** [RoderickQiu/wnr#41]
## How to reproduce (time interval <= 1)
1. Open wnr.
2. Set the values to "work for 1 minute, rest for 1 minute and loop for once".
3. The "all together" information does not come out but the timing functionality still works fine.

## How to reproduce (time interval is a float point value)
1. Open wnr.
1. Set the values to "work for 1.8 minute, rest for 1.1 minute and loop for once".
2. The "all together" information shows that there are all together 2 minutes. However, the exact value of the sum is 2.9 minutes which is closer to 3 minutes.

**Comment by RoderickQiu** [comment]
happy to see a bug fixed~
as someone who uses it all the time, it just seems that some user interaction started to get unnoticed for me..
