### ISSUE TITLE
增加时间四象限管理的建议

### ISSUE THREAD

**Issue by showkeyjar** [RoderickQiu/wnr#44]
使用单一沉浸式的闹钟模式，把人卡的像机器人，仅适合做简单任务
可否增加时间四象限管理？
很多时候需要完成的任务并不是固定时间的，也不是单一的
需要更多的自主性和任务重要性的管理

望采纳，谢谢！

**Comment by RoderickQiu** [comment]
对我来说，这可能更多意味着一个新的软件，因为在我的定位里wnr更多是一个计时软件，而非一个任务管理解决方案。因此，简单来说，我可能不会添加此功能，你暂时可以使用正计时模式，如果你对这一模式有基本流程或使用体验上的要求，请提出。
