### ISSUE TITLE
Option to disable "skip current timer".

### ISSUE THREAD

**Issue by ToTheMoon1234** [RoderickQiu/wnr#45]
I think it would be great if there was an option to disable the "skip current timer" option which we get while a timer is running. It would be helpful especially in the lock mode. In the lock mode you can't give up the schedule(you need a password to go back) but you can easily skip through all the sessions by using "skip current timer". If we have to use our laptops (can't turn on fullscreen mode while we are using it) then it is kind of like a loophole to turn off the timer. 
![image](https://user-images.githubusercontent.com/73231423/127530109-ca8182bc-6795-419f-9977-fc32b21bde6a.png)

Thanks!
It would be awesome if disabling "skip current timer" is made a global option and not just for lock mode (maybe separate option to turn it on/off for work time and for rest time like there is currently for pausing)

**Comment by RoderickQiu** [comment]
This seems to be a small patch so I'm currently able to do it fast, maybe within this week.

**Comment by RoderickQiu** [comment]
It has been finished, and an update will be there soon :D
