### ISSUE TITLE
[Feature Request] - Enhencement - Custom alarm sound and theme

### ISSUE THREAD

**Issue by AdrienDSlone** [RoderickQiu/wnr#46]
Hi wnr,

I was looking for an Hourglass alternative and wnr really is better!

Just to improve it, I would recommand custom alarm sound and also custom theme :)

Anyway, I am using it and will speak about,

thanks,,

**Comment by RoderickQiu** [comment]
Well, wnr do have settings->personalization to set custom sound and, if you want, you can send your audio and I can add your sound to the sound list, but I currently don't have enough time to rewrite the api to support local music files to be set.

As for the custom theme feature, you can describe it clearer as it's something everyone has his/her own thinking. - But anyway, I'm afraid my spare time can only support me to fix bug currently, but not to write something big really (sorry). However, in case you are equipped with frontend techstack and you are willing to help, I will be glad to co-develop :)
