### ISSUE TITLE
Please make Ui more inline with  windows 11 and use latest backend and less ram 

### ISSUE THREAD

**Issue by fisforfaheem** [RoderickQiu/wnr#49]
Please make Ui more inline with  windows 11 and use latest backend and less ram

**Comment by RoderickQiu** [comment]
Rewrite it using latest tech stacks like flutter can solve the ram problem brought by electron but I'm not interested frankly. As for the UI, you can see it is not in the same style with win10 so we will never use a win11 style and will keep use our own style.

**Comment by fisforfaheem** [comment]
Ok, But can u pledge to use latest electron version??? it has many new
benefits



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality9&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality9&>
10/02/21,
03:40:33 PM
