### ISSUE TITLE
这么好，而且小巧的应用希望能增加微软应用商店版本

### ISSUE THREAD

**Issue by wlos** [RoderickQiu/wnr#5]
如题，现在的应用下载时或提示有风险。希望能增加Microsoft Store 版本，能在应用商店直接安装。

**Comment by RoderickQiu** [comment]
提示有风险那也没办法……毕竟没有签名过。

Microsoft Store可以考虑。

**Comment by RoderickQiu** [comment]
目前差不多做好了准备工作，可能下周会上线msstore。

**Comment by RoderickQiu** [comment]
已经上架Microsoft Store。
