### ISSUE TITLE
Removed this bullish app that didnt let me use my own PC for 5 mins

### ISSUE THREAD

**Issue by fisforfaheem** [RoderickQiu/wnr#50]
it was so much important for me to see my desktop but this app is like a virus...didn't even let me close it at all

**Comment by RoderickQiu** [comment]
Well, if you're not a first-time user, I think it should be clear enough that if you come up with fullscreen focus mode, you cannot exit, which is the original purpose of the app. In case you don't feel like it, you should turn the weak mode on in settings. If you do have suggenstion, please state it clearly.

**Comment by fisforfaheem** [comment]
I didnt found any weak versio though! pleas emake it visible



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
10/02/21,
03:41:23 PM

**Comment by RoderickQiu** [comment]
Click the menu button on the left top of the index page and go to Global Settings, scroll down, turn Loose fullscreen mode on.

From @RoderickQiu


________________________________

**Comment by fisforfaheem** [comment]
Thanks, I'll check it out.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
10/06/21,
01:20:43 AM
