### ISSUE TITLE
双屏显示器，只有一个屏幕进入专注模式

### ISSUE THREAD

**Issue by ccw1078** [RoderickQiu/wnr#52]
系统：win10，
wnr: 1.23.2
设备：笔记本电脑，外接一个显示器，扩展模式（即显示器的屏幕也处于使用状态，笔记本为副显示器，外接为主显示器）

wnr 界面放置在笔记本屏幕中（副显示器），到了休息时间，只有笔记本屏幕进入休息状态，外接的显示器仍然处于工作状态（即鼠标和键盘可正常使用，但每隔几秒钟，键盘会失去焦点

**Comment by RoderickQiu** [comment]
@NKID00 好高级，去看看是不是相关问题。
不过我本地刚刚用Twomon USB配置了一个拿手机作为显示器的东西。目前仅在1.23.2的测试结果是假如在被设置为主显示器的屏幕上打开wnr可以使用，在副显示器上开启则不能使用。
需要再经过研究。

**Comment by RoderickQiu** [comment]
@NKID00 我目前已经完成了对1.23.2的安装/7z版、1.21.0安装、1.20.1安装的测试（仅测试64位，但32位是不会产生区别的），基本可以认为我在20分钟前的猜想是正确的，不过这只是基于我使用Twomon USB的测试。可以阐述一下

> 放在显示器 2 中也能复现。

的方式吗？

**Comment by RoderickQiu** [comment]
@ccw1078 你可以测试一下把wnr主界面放置于被设置为主显示器的那块屏幕是否解决问题。具体为什么会这样有待具体看代码再调试，那个代码也是我一年前写的了。不过，下周才会发布对这个问题的fix，估计会是一个新的小版本。
@NKID00 下个小版本可以将linux版本加入下载列表了吗？

**Comment by NKID00** [comment]
但是测试过还是会复现，说不定是VirtualBox的锅…

再怎么说 Setup 版会复现，7z 版就不会复现也太奇怪了。我试试对比下这两个安装目录下的文件？

GNU/Linux 版本应该不用管用户体验能跑就行，用这玩意的基本上都有能力解决或者强迫自己忽略bug（

**Comment by NKID00** [comment]
> @NKID00 我目前已经完成了对1.23.2的安装/7z版、1.21.0安装、1.20.1安装的测试（仅测试64位，但32位是不会产生区别的），基本可以认为我在20分钟前的猜想是正确的，不过这只是基于我使用Twomon USB的测试。可以阐述一下
> 
> > 放在显示器 2 中也能复现。
> 
> 的方式吗？

就是把wnr窗口拖到第二个虚拟监视器上然后开全屏专心。

**Comment by RoderickQiu** [comment]
啊这。那就先等@ccw1078 反馈。下周再说。

**Comment by ccw1078** [comment]
> 啊这，我以前是写过多显示器支持的，难道现在这玩意已经坏了？？ 然而我没有显示器，都是靠别的方式测试的，比较麻烦一些，稍后可能会尝试测试一下。 不过，假如把wnr界面放在外接显示器中，会如何？

把 wnr 界面放在外接显示器中，能够正常工作，即当进入休息时间时，外接显示器显示休息倒计时，笔记本显示器显示 wnr  的 LOGO （没有倒计时）

**Comment by RoderickQiu** [comment]
了解了。那就是之前的代码对主窗口放在副显示器的行为不能正常处理，需要修一下。最近学业繁重，大概下周末会修掉这个bug。至于@NKID00 你说的情况也许和VirtualBox兼容性有关。

**Comment by RoderickQiu** [comment]
bug修掉了，晚上发版本。
