### ISSUE TITLE
Transparent icon in latte dock in KDE

### ISSUE THREAD

**Issue by NKID00** [RoderickQiu/wnr#53]
```
OS: Kubuntu 21.10 x86_64
Kernel: 5.13.0-20-lowlatency
DE: Plasma 5.22.5
WM: KWin

lattedock 0.10.2
wnr 1.23.3
```

The icon is transparent in the [latte dock](https://github.com/KDE/latte-dock), but suddenly appears when the mouse hovers over it.

![Screenshot-1](https://user-images.githubusercontent.com/24316171/140609038-1f1e9ca9-acb0-41c8-a4ed-ae14acb21c8a.png)
![Screenshot-2](https://user-images.githubusercontent.com/24316171/140609035-e1c91684-0186-4dbf-8579-fa9cbcfe5e62.png)

This may be a issue of latte dock or Electron but I've never seen this problem when using other Electron-based apps. Other docks (task bars) shipped with KDE do not seem to have this issue.

**Comment by RoderickQiu** [comment]
Hello, anyway, is this problem still here?
