### ISSUE TITLE
打开软件弹出报错窗口 A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by CedarZ000** [RoderickQiu/wnr#55]
![Snipaste_2021-12-21_11-07-34](https://user-images.githubusercontent.com/96457243/146865617-ec1d0a5c-8e75-4999-8c75-801c8469082a.png)
![Snipaste_2021-12-21_11-35-05](https://user-images.githubusercontent.com/96457243/146866706-33162946-097c-498b-acac-52210f74560b.png)

非常感谢你开发这款软件。
打开软件时会先后弹出两个报错窗口，虽然点掉后还是能打开软件，但是预设功能用不了。卸载重装也没用，现在暂时使用其他替代品，但是还是觉得这款软件最好用。

**Comment by NKID00** [comment]
这看起来似乎是 wnr 使用的框架 electron 试图获取 Windows 版本时没有找到 PowerShell 而报错了，和 wnr 并没有直接关系。

请问你是在什么版本的 Windows 上运行的 wnr？是精简版还是原版 Windows？（PowerShell 貌似从 Windows 7 开始就自带了）

（或者可能这不是 Windows？）

**Comment by RoderickQiu** [comment]
除却精简版的情况，你可以检查一下：
1. 你是否打开了家长控制/应用白名单类软件？请把powershell加入白名单，这是由于wnr在启动检查时后台调用了脚本。
2. 是否安装了第三方安全软件？尝试关闭安全软件。如果确实如此，请把powershell和wnr所在目录不做检查。
3. 如果不是这样，请告知。
我春节期间会写一些更新，可能会对这样的情况做更好的兼容，假如你自查没能解决的话。不过近期还不会解决，因为准备考试中。

**Comment by CedarZ000** [comment]
> 除却精简版的情况，你可以检查一下：
> 
> 1. 你是否打开了家长控制/应用白名单类软件？请把powershell加入白名单，这是由于wnr在启动检查时后台调用了脚本。
> 2. 是否安装了第三方安全软件？尝试关闭安全软件。如果确实如此，请把powershell和wnr所在目录不做检查。
> 3. 如果不是这样，请告知。
> 
> 我春节期间会写一些更新，可能会对这样的情况做更好的兼容，假如你自查没能解决的话。不过近期还不会解决，因为准备考试中。

**Comment by CedarZ000** [comment]
> 这看起来似乎是 wnr 使用的框架 electron 试图获取 Windows 版本时没有找到 PowerShell 而报错了，和 wnr 可能并没有直接关系。
> 
> 请问你是在什么版本的 Windows 上运行的 wnr？是精简版还是原版 Windows？（Windows PowerShell 貌似从 Windows 7 SP1 和 Windows Server 2008 R2 SP1 开始就自带了）

![Snipaste_2021-12-25_22-31-06](https://user-images.githubusercontent.com/96457243/147387246-ed45c863-9e95-4a91-b051-fb1dae873a0a.png)
应该是原版的windows10 21H2，powershell也在的。但是我是小白所以不确定有没有删了什么东西。

**Comment by CedarZ000** [comment]
> 除却精简版的情况，你可以检查一下：
> 
> 1. 你是否打开了家长控制/应用白名单类软件？请把powershell加入白名单，这是由于wnr在启动检查时后台调用了脚本。
> 2. 是否安装了第三方安全软件？尝试关闭安全软件。如果确实如此，请把powershell和wnr所在目录不做检查。
> 3. 如果不是这样，请告知。
> 
> 我春节期间会写一些更新，可能会对这样的情况做更好的兼容，假如你自查没能解决的话。不过近期还不会解决，因为准备考试中。

感谢你的回答。

1. 并无安装类似的软件。
2. 安全软件只有火绒，尝试关闭安全软件后并打开wnr，情况还是一样。
3. 似乎是在我更新了windows10后，才出现了这个问题，但因为windows10的更新还是比较频繁的，所以我不确定是否存在相关性。也可能是我误删了什么东西。

再次感谢你的回答，目前问题虽未解决，但帮助良多。

另，祝你考试顺利。

**Comment by CedarZ000** [comment]
我意外地找到方法了，只需要给powershell添加环境变量就行了。
