### ISSUE TITLE
页面建议

### ISSUE THREAD

**Issue by YangFong** [RoderickQiu/wnr#56]
开始界面，在展开下拉框时，将右侧文本全遮盖住，感觉会更好

![image](https://user-images.githubusercontent.com/70502828/147846903-bb1744ac-f742-442f-92bc-c14a71f0df21.png)

---

另外发现，下拉框菜单有点不对劲，我对比了一下官网效果图，有差异存在，应该不是屏幕有污渍

![image](https://user-images.githubusercontent.com/70502828/147846928-17f218b9-1671-4eed-a5e3-3e8bdf1b6046.png)

![image](https://user-images.githubusercontent.com/70502828/147846958-acb7f354-f5f2-4860-95e2-0bfece52adc1.png)

我使用的版本是 1.23.3

**Comment by RoderickQiu** [comment]
收到。近期比较忙，节前会搞定。

**Comment by RoderickQiu** [comment]
今天晚上有点时间，等会搞一搞。不过相关更新肯定近期不会发，得等春节假期。

**Comment by YangFong** [comment]
> 今天晚上有点时间，等会搞一搞。不过相关更新肯定近期不会发，得等春节假期。

哈，期待后续的更新啦。

**Comment by RoderickQiu** [comment]
刚才搞了一会，搞定了。感谢建议。
