### ISSUE TITLE
Enhancement Request: whitelist and blacklist websites in working mode

### ISSUE THREAD

**Issue by snyang** [RoderickQiu/wnr#57]
The utility is amazing.
I hope there is a  feature which can prevent users from accessing some websites during working.
A whitelist websites to which users can access, or a blacklist websites to whicch users cannot access.

**Comment by RoderickQiu** [comment]
It is a good feature, but I'm currently too busy to make it. Moreover, implementing native code for electron apps is a burden and I am not familiar with those native apis. 
Personally, I am using Time Boss _(and you can find registration keys of it online in case you wanna try)_ when I want to block websites and apps as I don't think it is a feature firmly related to wnr.
