### ISSUE TITLE
正计时中消失的跳过按钮

### ISSUE THREAD

**Issue by YangFong** [RoderickQiu/wnr#60]
**简述**

正计时功能在进入时缺少跳过按钮，只有在 MINI 模式下才能触发，后续则恢复正常，

---

**情况说明**

是这样的，我常常使用正计时，通常是这个样子：

![image](https://user-images.githubusercontent.com/70502828/155815765-82ced3a3-a9b5-4e08-b034-622af4f2c0f2.png)

某天发现 MINI 模式下有两个结束按钮，我就按下了右边的，

![image](https://user-images.githubusercontent.com/70502828/155815919-768bec0d-6fec-4b87-a2d5-a4be11718ac6.png)

突然发现，这是进入休息时间的。

![image](https://user-images.githubusercontent.com/70502828/155815877-7b8bfa00-d468-4ceb-9d14-a2770a150915.png)

而在此之前，我倒是一直不知道还有这一层，因为没有跳过按钮。

![image](https://user-images.githubusercontent.com/70502828/155816086-14b23a2b-9cca-464b-9eae-a241393c8459.png)

**Comment by RoderickQiu** [comment]
啊这，我原本正计时就是不跳过的。可能mini模式写bug了。或者说你很喜欢这个buggy feature？

**Comment by YangFong** [comment]
@RoderickQiu 我个人倒是挺是很适合这种使用，不带任何强制，有时休息，懒得退出去开全屏了，一键进入即可，就单纯计时。

当然这都是昨天偶然发现的，今天整理一下提出这个 issue。我是偏向将按钮显示出来，😁而不是修正 mini 模式，使用选择让用户自己去决定吧。

**Comment by YangFong** [comment]
我观察到 1.25.0 当中落实了这个方案，Happy
