### ISSUE TITLE
Request: more sound adjustment options

### ISSUE THREAD

**Issue by Funny-Klutz** [RoderickQiu/wnr#62]
Can the developers please include notify sound volume adjustment options, along with the ability to mute the sounds in the next update or in other upcoming updates? The alarms are often too loud to listen to, especially while watching University lecture videos, for example.

Edit: wishing the developers all the very best for the Gaokao exam!

**Comment by RoderickQiu** [comment]
Hello, the function to mute the sound has actually been added and you can search in settings panel to find it. Altering sound volume is a fantastic idea, but I might not add it before June for I am busy on exam preparation. Thanks!

**Comment by Funny-Klutz** [comment]
I was unable to find the option for doing so, but I will not disturb you any further for now because of your exam. Wishing you all the very best! 😁

**Comment by Funny-Klutz** [comment]
Hello Roderick. I hope your exam went well. My Wnr version is v1.24.0, and I cannot find the "Play the notify sound" option. My operating system is Windows 11.

![image](https://user-images.githubusercontent.com/101057072/174482443-837600ab-2802-4903-bc30-5f67312707ec.png)

**Comment by RoderickQiu** [comment]
Hello, this feature is now added in the new v1.25.
<img width="631" alt="图片" src="https://user-images.githubusercontent.com/42290260/176649067-ff5e699e-f144-40ed-a40d-44b8735fd4ee.png">
And is called "volume of notify sound". Thanks for waiting!
