### ISSUE TITLE
关于更好的字体显示

### ISSUE THREAD

**Issue by EthanVn** [RoderickQiu/wnr#67]
你好, 很喜欢这个软件, 简洁大方, UI也很好看
但是作者是不是在Window笔记本下分辨率125%的环境下开发的
笔者在1920*1080下100%使用软件时, 字体略小, 影响不大, 但无法最大程度发挥软件绝美的UI设计
![image](https://user-images.githubusercontent.com/83664895/164374004-01a8586f-7ce8-46b6-97c0-d3d67cac1a6e.png)
在1920*1080下125%显示可以得到很棒的效果
![image](https://user-images.githubusercontent.com/83664895/164374218-e9dd57c9-6bd2-4857-b202-e636d317ca5d.png)
作者大大有没有意向适配使得软件在100%显示下也能有很好的显示效果呢
个人的思路是添加一个大号字体按钮, 启用时字体变大, 使其适配100%显示的屏幕

**Comment by EthanVn** [comment]
或者整个网页125%放大, 应该也可以解决问题

**Comment by RoderickQiu** [comment]
抱歉一直没回，之前在准备高考。
我刚刚查了一下，有个叫

        const { webFrame } = require('electron')
        webFrame.setZoomFactor(1.25)

的API将可以解决这个问题，将在下个版本中提供放大/缩小文字的设置项以满足你的需求。

**Comment by RoderickQiu** [comment]
已解决，将附带在下个版本中发布。
<img width="390" alt="图片" src="https://user-images.githubusercontent.com/42290260/174005166-5b56d639-7dd7-4968-a703-1d064ae5e52f.png">

**Comment by EthanVn** [comment]
可以的可以的强的
