### ISSUE TITLE
建议只能仅存一个进程

### ISSUE THREAD

**Issue by ZSXB2468** [RoderickQiu/wnr#68]
程序可以重复启动，在家长模式下，还无法关掉多余的程序
建议限制程序只能存在一个进程
![image](https://user-images.githubusercontent.com/62994932/167310594-c1650910-a765-4b86-88cc-aa4f6209dfd4.png)
![image](https://user-images.githubusercontent.com/62994932/167310584-89d0cec5-fb1b-4824-a5e0-adb4af90de08.png)
![image](https://user-images.githubusercontent.com/62994932/167310636-1ec182a8-67f1-438a-87ab-81d8b19bfc9a.png)

**Comment by RoderickQiu** [comment]
你好，新版已经发布，应当解决了问题。
