### ISSUE TITLE
时间剩余存在一点问题。

### ISSUE THREAD

**Issue by xxstop** [RoderickQiu/wnr#7]
![image](https://user-images.githubusercontent.com/4318498/78852525-20d42300-7a4f-11ea-872e-42169660bbcf.png)

**Comment by RoderickQiu** [comment]
嗯…这是一个JavaScript的历史遗留问题，我本来不想管了...
当然 既然有人看了难受，下个版本将会解决这个问题。
大概这周末会发布v1.15.0，请关注。

**Comment by xxstop** [comment]
哈哈，还有就是任务栏的图标可以搞样式吗？

**Comment by RoderickQiu** [comment]
任务栏的图标你希望有什么效果／可以怎么改？

**Comment by xxstop** [comment]
可以搞个动态图标之类的东西么？这样也可以直观的看着剩余的工作时间；
还有一个问题呀，我这儿的剩余一分钟提醒勾了咋不起作用，就没有提醒过我。

**Comment by RoderickQiu** [comment]
> 可以搞个动态图标之类的东西么？这样也可以直观的看着剩余的工作时间；

现在在计时时，如果不是隐藏到托盘菜单，则任务栏上有进度条；而鼠标悬停在托盘菜单图标上也会有进度提示；我个人认为是直观的。如果你认为这样不符合你的工作流，请指出。毕竟动态图标可能会需要一些工作量。

> 还有一个问题呀，我这儿的剩余一分钟提醒勾了咋不起作用，就没有提醒过我。

不清楚。本地我看看我自己的代码是没有事情的，我自己也能正常接到提醒。你可以在wnr的设置里把当前设置项导出一下我看看。

此外，我建议你看看是否允许了wnr发出应用通知。如果关闭了应用通知，那通知将会无法显示。

**Comment by xxstop** [comment]
理解，辛苦~

我这边使用的便携版本，可能会存在权限问题？

### 通知
关于软件的配置为：
`
{
	"i18n": "zh-CN",
	"hotkey1": "Alt + Q",
	"hotkey2": "Alt + D",
	"just-launched": false,
	"fullscreen-protection": false,
	"isdark": true,
	"predefined-tasks-created": true,
	"predefined-tasks": [
		{
			"name": "wnr recommended",
			"workTime": 30,
			"restTime": 6,
			"loops": 5,
			"focusWhenWorking": false,
			"focusWhenResting": true
		},
		{
			"name": "pomodoro",
			"workTime": 25,
			"restTime": 5,
			"loops": 4,
			"focusWhenWorking": false,
			"focusWhenResting": true
		},
		{
			"name": "class time",
			"workTime": 40,
			"restTime": 10,
			"loops": 1,
			"focusWhenWorking": true,
			"focusWhenResting": false
		}
	],
	"default-task": 0,
	"is-shadowless": true,
	"last-check-time": 1586182757435,
	"tour": "true",
	"islocked": false,
	"never-sent": false,
	"settings-goto": "normal",
	"settings-experience": true,
	"sound": false,
	"alarmtip": true,
	"onemintip": true,
	"infinity": true,
	"top": true,
	"just-relaunched": false,
	"all-end-sound": "magic",
	"time-end-sound": "whistle",
	"last-recorded-state": {
		"workTime": 30,
		"restTime": 6,
		"loop": "0",
		"title": "",
		"note": "",
		"isWorkTimeFocused": false,
		"isRestTimeFocused": true,
		"method": 1
	},
	"last-recorded-hours-left": -1,
	"last-recorded-minutes-left": -1,
	"autostarttask": true
}
`

Win Server 2019系统通知配置：
![image](https://user-images.githubusercontent.com/4318498/79037783-ad751180-7c06-11ea-9f52-aa6838073b47.png)

**Comment by RoderickQiu** [comment]
我使用你的设置，添加到便携版里，正常提示了还剩一分钟。

需要提醒的是，在全屏专心模式时，通知不会显示，所以我会模拟系统通知的一声提示音，在像你一样关闭提示音设置之后就没有这一声提示音了，但依然会静默提示还剩一分钟。
工作模式时候会正常提示还剩一分钟的通知，包含一声提示音。

你可以测试1.1分钟的工作时间，然后应当可以在5秒后收到提示。

我是Windows 10 Pro v1909，有“专注助手”，不知道你在你的系统中有没有打开。打开“专注助手”后，通知可能不会显示。在Windows10系统上，wnr没有被注册在通知发送者列表中，但应该也是可以发送的。

如果实在不行且你觉得有必要解决这一问题，你可以在 https://r-q.name 上找到我的QQ。或者你可以看看普通安装版是否可以正常通知，如果可以的话，你可以导入设置到安装版中使用。

谢谢反馈。

**Comment by xxstop** [comment]
是的，我这儿是将提示音给关闭了。然后我刚刚设置了一下1.1分钟的工作时间。最后Win Server 2019系统没有做出任何的响应。待我安装安装版本试试。

![image](https://user-images.githubusercontent.com/4318498/79040488-6ba29600-7c1b-11ea-9cf5-154c684737d3.png)

1.1分钟的配置如下
![image](https://user-images.githubusercontent.com/4318498/79040506-8e34af00-7c1b-11ea-9a31-08c8cd7dc8a2.png)

**Comment by xxstop** [comment]
最新的版本已经在干净的windows server 2019服务器上进行测试过了。

安装版和便携版都无法1分钟进行提醒，感觉跟系统有很大的关系~

**Comment by RoderickQiu** [comment]
可以下载1.15.1了～

**Comment by ihewro** [comment]
![image](https://user-images.githubusercontent.com/20165605/114189553-e57b7580-997c-11eb-9a35-b25bf3081d63.png)
Mac 端似乎没有申请通知的权限，所以这里面找不到，我设置了任务结束前一分钟提醒，也没有提醒

**Comment by RoderickQiu** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/20165605/114189553-e57b7580-997c-11eb-9a35-b25bf3081d63.png)
> Mac 端似乎没有申请通知的权限，所以这里面找不到，我设置了任务结束前一分钟提醒，也没有提醒

@ihewro  是terminal-notifier，因为我使用了一个第三方类库。
一直想要在某个地方提醒用户这件事，但没有想好应该放在哪，你觉得放在哪比较合适？

**Comment by ihewro** [comment]
@RoderickQiu  感谢回复！ 有个声音和通知对我来说就够了，感谢开发这么强的软件 💯
