### ISSUE TITLE
单纯计时建议

### ISSUE THREAD

**Issue by godingchen** [RoderickQiu/wnr#70]
应该取消工作结束了的弹框，感觉没有必要。

**Comment by RoderickQiu** [comment]
抱歉一直没回复，因为此前在准备高考。
你的建议是很有道理的，我看看能否取消掉它，现在有这个纯粹是写的时候为了省事，但应该是可以操作一下来去掉的。

**Comment by RoderickQiu** [comment]
昨天已经完成了，将体现在下一个版本中。
