### ISSUE TITLE
关于计时的建议

### ISSUE THREAD

**Issue by Angusfly** [RoderickQiu/wnr#71]
可否增加通过监测鼠标、键盘动作记录实际的工作时间？现在如果中途离开，依旧会计算工作时间。

**Comment by RoderickQiu** [comment]
对一直未能回复抱歉，因为在准备高考。
你的建议值得考虑，也许会被加入wnr，但我还不能确定。

**Comment by boykensoidong** [comment]
> 可否增加通过监测鼠标、键盘动作记录实际的工作时间？现在如果中途离开，依旧会计算工作时间。

try pandan app on macos: 
https://apps.apple.com/us/app/pandan/id1569600264?mt=12
