### ISSUE TITLE
全屏专心模式怎么开启？

### ISSUE THREAD

**Issue by Young-Flash** [RoderickQiu/wnr#72]
win11 系统，到休息的时候没有自动开启全屏专心模式，在设置里面好像也没有开启全屏专心模式的按钮，到休息的时候只出现了小框框
![image](https://user-images.githubusercontent.com/71162630/173982116-a7d0f318-b7cb-4519-97ed-cade6b715601.png)

**Comment by RoderickQiu** [comment]
<img width="461" alt="图片" src="https://user-images.githubusercontent.com/42290260/173982988-85eddfab-7d3f-4943-9870-bb90d67faac2.png">
你指的是这个么？

**Comment by RoderickQiu** [comment]
另外，最适合日常使用的方式是设定一个预设任务，并将其默认自动启用。

**Comment by Young-Flash** [comment]
是的，原来是在这里开启。谢谢大佬！！！做得很棒
