### ISSUE TITLE
1.25.0 MINI 模式窗口大小异常

### ISSUE THREAD

**Issue by YangFong** [RoderickQiu/wnr#73]
当前所观察到的尺寸是 1002x752，并不能进行大小大小调整（尝试在边界获取拖拽修改）。

![image](https://user-images.githubusercontent.com/70502828/176646055-a90e6e99-5200-4bcf-bb33-dfc184e296dc.png)

![image](https://user-images.githubusercontent.com/70502828/176646684-145caef3-bfa9-4a48-9717-30b9772bb3ce.png)

**Comment by RoderickQiu** [comment]
不过，话说，感谢这么快就更近到1.25了

**Comment by YangFong** [comment]
> 啊这，我这边使用windows11和macOS均无法复现你的效果。 麻烦设置里备份statistics和settings之后尝试清空一下%APPDATA%/Roaming/wnr试试？你这个情况我属于从未见到过了……

没能成功，把另一个问题解决了（跟随系统主题），MIUI 窗口还是那么大，我的环境处于体验版 window11

**Comment by YangFong** [comment]
晕了，我刚刚在设置当中调整了一下缩放比例，居然又正常了。

也就是先将尺寸调小，查看 MIUI 窗口尺寸如何，发现是正常的大小，调整回来，默认比例也正常了。

**Comment by YangFong** [comment]
当前可以确定是，重新安装之后尺寸依然会异常，通过调整缩放比例才能恢复正常（调小再调大）。

刚更新时我还以为新版本设置界面就是这样的，后续发现也是异常的。

![image](https://user-images.githubusercontent.com/70502828/176801142-6b5078cc-2e6c-44db-84bd-16a74eb723d9.png)

![image](https://user-images.githubusercontent.com/70502828/176801243-91fc3e61-a785-4386-9ae6-dafe8dff503a.png)

**Comment by RoderickQiu** [comment]
emmmm……那可能是我缩放api写出锅了qaq
