### ISSUE TITLE
MINI模式窗口大小异常

### ISSUE THREAD

**Issue by NoHeartPen** [RoderickQiu/wnr#74]
更新到1.25.0后MINI模式窗口和以前的大小不一样了，是专门这样设计的么（个人感觉还是以前的那种小小的方块置顶的感觉更好）
<img width="960" alt="2022-07-11_13-23-49" src="https://user-images.githubusercontent.com/79316356/178194449-19737419-fd21-4c11-9833-b9e3637026c2.png">

我是前天更新的，发现MINI模式的界面变化后以为是自己的更新方法不对（解压后直接覆盖原来的安装路径），重装了2次（用过卸载工具Revo.Uninstaller.Pro清理过卸载残留）都没有回复之前版本的MINI模式的大小。

请问如果是Bug的话，我需要提供那些信息呢？

其他模式的大小还是正常的<img width="960" alt="2022-07-11_13-23-32" src="https://user-images.githubusercontent.com/79316356/178194409-5a643a99-f35e-433e-9bdf-a4407d4f73c7.png">

**Comment by RoderickQiu** [comment]
你好，这一问题此前我已知悉，但限于时间一直没修。今天比较空，已经修掉了，会待会在1.25.1版本中呈现。
