### ISSUE TITLE
可优化的设置导入

### ISSUE THREAD

**Issue by YangFong** [RoderickQiu/wnr#75]
发现一个小问题，导入设置时，我的设置配置是勾选了开机自启的，但是导入之后，虽然显示的是开启，但实则没有。当然，我可以重新开关一下，就能成功创建开机自启。

那么，是否可以在导出设置的时候，将开机自启选项给忽略掉呢，又或者导入的时候，完成开启自启功能。

![image](https://user-images.githubusercontent.com/70502828/181025891-f51ce832-51c7-4f3f-a0ee-38ff94779887.png)

**Comment by RoderickQiu** [comment]
很有道理，会在之后添加，谢谢支持。

**Comment by RoderickQiu** [comment]
之前忘做了，现在已经修复。
