### ISSUE TITLE
Auto switch Dark mode seem didn't work on Win11/自动切换深色模式似乎在Win11上不起作用

### ISSUE THREAD

**Issue by NoHeartPen** [RoderickQiu/wnr#77]
翻了一下issue，似乎没人报过类似的错误，所以用英文也写了一遍。但是我英语水平实在令人捉急，所以接下来还是用中文吧。

（GitHub不能显示gif，所以以链接形式插入）

[https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Video_20220810174839.gif](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Video_20220810174839.gif)

如上面的动图所示，wnr的“跟随系统切换”在Win11上似乎并不起作用（多次重启也不行），考虑到electron的内核是chromium，应该可以做到像浏览器切换网页的主题一样——即使软件已经打开，也可以不重启直接切换为深色模式。

最初以为是因为自己使用了第三方工具[Auto Dark Mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode)——我以为这款软件并没有影响系统的值，设置里面可能仍旧是浅色模式。

不过去设置查看，发现设置里面的值已经被设置为深色了。

![](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Pasted_image_20220810164356.png)

然后尝试在设置里手动更改颜色模式，发现wnr也没有跟随系统切换，反复重启软件wnr还是浅色模式。

系统版本是Win11，wnr软件版本1.25.1

我不确定之前的深色模式是否正常，因为我也是在翻译wnr时才发现原来支持跟随系统深色模式:)
![](https://markdoen-1304943362.cos.ap-nanjing.myqcloud.com//Pasted_image_20220810171551.png)
我注意到在我fork的时候你似乎已经注意到部分系统有可能会存在这个问题，但在最新的代码中已经找不到相关的表述，所以才来报告。

另外，我测试了下Obsidian（也是基于electron技术开发）：即使我用第三方的工具来切换深浅模式，它也可以在不重启的前提下切换深浅模式，所以也许是有这样的API吧。

~~但我不懂JS，所以就只能絮絮叨叨写这么长，来表达一个用户的殷切期望啦~~

**Comment by RoderickQiu** [comment]
你好，我测试了一下，使用Windows 11 22622.436，最新版AutoDarkMode和最新版wnr，成功实现了模式切换。
然后用系统设置，也成功了。不知道是否和我的Win11是在虚拟机中运行有关？还是和你的AutoDarkMode版本有关？

**Comment by NoHeartPen** [comment]
好的，我也检查了下，看起来是和Win11在虚拟机中有点关系：
我的Win11版本号22000.795（通过系统推送升级，电脑购买激活后没有折腾过，官网可以查到授权）
wnr也是最新版，使用`wnr-1.25.1-Setup-x64.exe`安装（之前用的zip文件解压然后覆盖的方法，上个月更新后改用exe文件了，重装前用Revo.Uninstaller.Pro.4.1.5清理过残余）
AutoDarkMode也是最新版，来自GitHub的`AutoDarkModeX_10.1.0.10.exe`文件

另外，我也用虚拟机测试了下，用AutoDarkMode也可以使最新版的wnr自动切换成功。（虚拟机上的Win11未激活，所以我不能通过系统设置手动更改颜色模式。用AutoDarkMode更改后，系统设置的值也跟着更新了，但我是点不动切换的按钮的）

![image](https://user-images.githubusercontent.com/79316356/184287684-c1467d1e-bbe3-4e7d-b76f-fbf9cca23ce9.png)

虚拟机Win11版本 22000.318
虚拟机软件版本Vmware 16.2.3 build-19376536

**Comment by YangFong** [comment]
确实存在一定的问题，即便当前系统为浅色，应用主题选择了跟随系统，却依然为深色主题。

![image](https://user-images.githubusercontent.com/70502828/184645283-b9607392-7238-4a67-b7d8-04320ead8ae4.png)

**Comment by RoderickQiu** [comment]
你好，我刚刚查看代码之后发现是一个很低级的小错误导致了大麻烦……刚刚修好了，然后感谢@YangFong 帮我也做了一些工作。谢谢issue和pr🙏

**Comment by RoderickQiu** [comment]
不过由于接下来我会比较忙，大概在十天后我才会发布新版本修复这个问题，请谅解🤝
