### ISSUE TITLE
windows10双屏幕问题

### ISSUE THREAD

**Issue by Daydreamer-Zhen** [RoderickQiu/wnr#8]
在win10下屏幕投影的复制模式下只有主屏幕会自动解除专注模式,次屏幕会保持专注模式的屏保无法自动退出。

**Comment by RoderickQiu** [comment]
看来是测试疏漏了。我只进行了Extend模式屏幕的测试，而没有进行Duplicate模式的测试。很大的问题。

抱歉带来了不便，请等待这周末将会上线的新版本。

**Comment by Daydreamer-Zhen** [comment]
> 看来是测试疏漏了。我只进行了Extend模式屏幕的测试，而没有进行Duplicate模式的测试。很大的问题。
> 
> 抱歉带来了不便，请等待这周末将会上线的新版本。

除此之外体验挺良好的,加油🎉

**Comment by RoderickQiu** [comment]
我今天debug了一下，发现是之前一个函数传参出了问题……可能还是对编程语言理解不够深刻吧。现在解决了。

新版发布后，这个issue将会被关闭。

**Comment by Daydreamer-Zhen** [comment]
> 我今天debug了一下，发现是之前一个函数传参出了问题……可能还是对编程语言理解不够深刻吧。现在解决了。
> 
> 新版发布后，这个issue将会被关闭。

自己造轮子已经很不错了,不像我这种咸鱼哈哈哈

**Comment by RoderickQiu** [comment]
1.15.0已经发布～你可以看看问题是否解决了。

**Comment by SpaceTime1999** [comment]
现在的话，使用两台显示器，工作专注模式只有一个桌面显示为专注模式。另一个桌面锁定的同时显示如常。

**Comment by RoderickQiu** [comment]
> 现在的话，使用两台显示器，工作专注模式只有一个桌面显示为专注模式。另一个桌面锁定的同时显示如常。

你是否开启了宽松的专注模式？如果可以的话给个图片。
