### ISSUE TITLE
主题系统未解决的问题

### ISSUE THREAD

**Issue by YangFong** [RoderickQiu/wnr#80]
暂时未找到解决方案，在此罗列一下我看到的：

- [ ] `darkModeChanges` 在更新时会触发两次（无伤大雅，可能无法主动控制）
- [ ] 设置窗口无法追踪系统主题变化

![动画](https://user-images.githubusercontent.com/70502828/186385623-462c24c1-c17b-4305-9a65-b78d1b1d05f8.gif)

**Comment by RoderickQiu** [comment]
暂时比较忙，过几天再看。

**Comment by RoderickQiu** [comment]
https://github.com/RoderickQiu/wnr/commit/249f5ba7380cce3e38990e4edc97da7565c1a73b 已经修复。
