### ISSUE TITLE
【建议】添加自定义流程的循环

### ISSUE THREAD

**Issue by szlysms** [RoderickQiu/wnr#81]
因为我们学校上完两节课有大课间和眼保健操，所以上午要自己先循环两次40+10再倒计时25再循环两次40+10，这样说实话有点太麻烦了，而且如果我上课上到一半突然想打开计时就需要自己算还剩多少时间然后去倒计时再在下一节课开始时用上课的40+10循环。
建议自定义初次循环剩余时间（比如我已经上课20min，我第一次循环就是20+10，第二次开始才40+10），再一个就是可以自定义第几次循环后可以有一次特殊的休息时间（比如第二次循环后就休息25min）
当然，我不能说我的要求是合理的，因为如果工具太过复杂可能会消耗太多精力，不过我觉得第一个“自定义初次循环剩余时间”的建议是必要的:D

**Comment by RoderickQiu** [comment]
<img width="417" alt="图片" src="https://user-images.githubusercontent.com/42290260/189087096-3c8aee1b-e40b-4349-97e0-f28e8d4369a2.png">
那个特殊休息时间的功能，你看看这个是否符合需求？还是要再如何？
关于所谓“自定义初次循环剩余时间”，我没有非常理解你的具体需求，请解释一下。

**Comment by RoderickQiu** [comment]
好的，可以考虑在下个版本中试一试，不过可能会等到十一假期。

**Comment by RoderickQiu** [comment]
今天稍微有些时间，想到了来做一做。现在的方案是在首页-》更多设置中添加一项“第一次工作时间减少几分钟”这样一个选项，你看看如何。

**Comment by szlysms** [comment]
> 今天稍微有些时间，想到了来做一做。现在的方案是在首页-》更多设置中添加一项“第一次工作时间减少几分钟”这样一个选项，你看看如何。长休息的那个过几天再说，不过已经想好方案了。

这正是我想要的：D
感谢你的付出❤
（很抱歉回复晚了，但是临近考试实在有点忙，不过我仍然会定期回复的）

**Comment by RoderickQiu** [comment]
今天稍后会发布新版本，包含你的两个需求。祝学习顺利。
