### ISSUE TITLE
结束时提醒窗口弹出到当前窗口

### ISSUE THREAD

**Issue by Benjamin-Watson0** [RoderickQiu/wnr#84]
当我全屏看视频并收到休息时间到的提醒时，我总是不是不退出全屏，有时候打开的窗口比较多，我不得最小化或者关闭其他窗口，然后才能看到提醒。

注意：我这里讲的是类似下图这种小窗口，主要是不叉掉这个小窗口他就一直响，在一些公共场合慌忙找到这个小窗口关闭响声显得很尴尬。
这个小窗口能弹出到当前窗口吗？

![图片](https://user-images.githubusercontent.com/112467275/190051293-12acd7b9-a814-4f4b-8da2-218e7fdee788.png)

**Comment by RoderickQiu** [comment]
这可能是Windows原生提示窗的局限性了…考虑在下一个版本中把原生提示窗换成自己的窗口，应该就不会有问题了。

**Comment by Benjamin-Watson0** [comment]
我下载了目前的最新版本，不清楚是不是改了。就是我正在看网课，然后到点了，休息全屏幕模式，我还没来的及关掉视频，全屏模式我也没办法操作，导致视频就还继续播放（我可以听见声音）
要不要给个机会让我可以进行暂停视频的操作。
我不清楚要怎么做，但我观察到是先弹出全屏，然后再弹出提示休息的小窗口，要不要点击确认之后再全屏？

**Comment by RoderickQiu** [comment]
你好，前几天比较忙，忘记回复了。下一个版本目前还没有发布，所以现在的最新版本肯定是没有改的。不过你的补充说明让我了解到我之前对你的需求的理解是错误的，我到时候重新审视一下应该如何解决这个问题。

**Comment by RoderickQiu** [comment]
我又思考了这个问题，发现以下事实：改成确认再全屏会严重影响软件的强制性，我认为，因为你可以一直挂着那个提示框不确认，所以除非你认为非常必要，否则我可能确实得斟酌一下，因为这个需求设计到我很多逻辑要改动，而且需要大量测试确保不出问题。我的替代方案是增加一个设置项，在时间结束前多少秒提示你一次将要结束，然后提示后不再允许暂停和退出，这样仍然是强力的。你看如何？

**Comment by RoderickQiu** [comment]
做完了你这个功能，但新版本可能还要过几天。你如果需要新版，可以回复我你使用的版本。

**Comment by Benjamin-Watson0** [comment]
> 做完了你这个功能，但新版本可能还要过几天。你如果现在就需要这个功能，可以回复我你使用的版本，我发你个链接。

太好了，我已经好久没看消息了。。见谅

**Comment by RoderickQiu** [comment]
今天稍后会发布新版本，包含这一功能。
