### ISSUE TITLE
关于提供关闭显示时间选项的建议

### ISSUE THREAD

**Issue by Benjamin-Watson0** [RoderickQiu/wnr#85]
你好，我在使用中遇到使用电脑学习过程中遇到一点小苦恼，我发现显示时间会减少我的积极性。比如当我看到时间为11：20时，我就会想到要吃饭了，本来学的很好，就有点懈怠。电脑上右下角时间已经关了，平常会使用这软软件来辅助学习（说到这里要感谢一下开发者的无私付出）
忘我工作小秘诀，不看时间！！
恳请您能提供关闭时间显示的选项
再次感谢您的付出。

![图片](https://user-images.githubusercontent.com/112467275/191210808-d9836298-816d-4f13-8496-f469c64f88ea.png)
![图片](https://user-images.githubusercontent.com/112467275/191208112-18dc3704-2c76-45b9-b112-d85ef23a75f4.png)
![图片](https://user-images.githubusercontent.com/112467275/191208317-0ecabe09-f2c0-4d41-b229-a11909daf647.png)
![7c80c53679c7854c227e087969c13ad](https://user-images.githubusercontent.com/112467275/191208416-b3d26a7e-2e72-4226-826d-ab40320ac3e5.jpg)
![9aa0cf7ac5efe75ab89cb3000cc8f3d](https://user-images.githubusercontent.com/112467275/191208440-22059580-9d54-4475-9ca2-c7196925cf69.jpg)

**Comment by Benjamin-Watson0** [comment]
您看到可以恢复下吗

**Comment by RoderickQiu** [comment]
你好，你的建议有道理，将加入到下一版本中。

**Comment by RoderickQiu** [comment]
写完了，会加入在下一个版本中。不过由于可能还有别的一些功能要写，可能不会在几天内发布。
