### ISSUE TITLE
JavaScript 报错，软件无法关闭

### ISSUE THREAD

**Issue by ZXYFrank** [RoderickQiu/wnr#87]
![image](https://user-images.githubusercontent.com/49837632/212068130-a9608b18-e1c3-4203-b35e-5c8d2a814588.png)

感谢你的软件 ❤️ 

还有一个问题：软件没办法卸载了

![image](https://user-images.githubusercontent.com/49837632/212068620-47bd166f-d9d1-4fc5-8808-317b1b0f3896.png)

![image](https://user-images.githubusercontent.com/49837632/212068675-e1eaaaf0-821f-413f-9c48-830d8d64635b.png)

**Comment by ZXYFrank** [comment]
现在只能通过手动删除安装文件夹内的文件，重装，才能卸载

**Comment by RoderickQiu** [comment]
发现大概是一个偶发的主界面崩溃事件后，退出前的一个操作没有对win==null时做特判导致的。目前已经在 [#ccf2d61](https://github.com/RoderickQiu/wnr/commit/ccf2d61659b002dc8ea35e960a731df76e21cd11) 中修复，然后这个问题我猜测发生概率并不高，也并未复现，所以就先不发版本了。不过还是感谢你的反馈。

**Comment by ZXYFrank** [comment]
感谢！
