### ISSUE TITLE
"wnr.app" is damaged and can't be opened Error on mac ventura

### ISSUE THREAD

**Issue by HastyPterygoid** [RoderickQiu/wnr#88]
Love this addon, but it seems mac is making it more difficult to use apps from unverified developers. Reinstalling, rebooting, and updating did not fix the issue. I used the command below (to remove the file attributes) and that worked for now.

xattr -cr /Applications/wnr.app

**Comment by RoderickQiu** [comment]
OK, thanks for the notice. I myself haven't updated to Ventura yet so I haven't found this issue yet. Will add that notice later.

**Comment by RoderickQiu** [comment]
Added your notices on several places. Thanks for notifying me :D, as I can't afford the macOS license sadly :(
