### ISSUE TITLE
关于任务栏进度条的建议

### ISSUE THREAD

**Issue by luo-chuan** [RoderickQiu/wnr#89]
![screenshot1](https://user-images.githubusercontent.com/33930736/215648557-a0e11cea-0f14-457e-aa63-5f813d8634b8.png)
上图是番茄人生（[官网](https://www.tomatolist.com/)）软件的任务栏，我觉得有以下几点值得学习：
1. 区分休息和工作的进度条颜色，比如番茄人生的休息进度条是绿色，工作进度条是红色。
2. 在任务栏图标旁边显示剩余分钟数（或正向计时分钟数）。这样的话就不需要悬浮的mini小窗了，更加节省屏幕空间。
3. 在第2点的基础上，将进度条的走向改为从右到左，也就是剩余分钟数越多进度条越长，更加符合直觉。

**Comment by RoderickQiu** [comment]
好的，值得考虑，我过段时间研究研究

**Comment by RoderickQiu** [comment]
这个搞定了。

**Comment by luo-chuan** [comment]
> 这个搞定了。

厉害了，期待更新。
