### ISSUE TITLE
建议将缩小到状态栏按钮的图标更改

### ISSUE THREAD

**Issue by Marchlie** [RoderickQiu/wnr#9]
现有的状态栏图标看起来就像是下拉菜单，每次想打开设置都会不小心缩小到状态栏，建议换一个图标

**Comment by RoderickQiu** [comment]
好。

**Comment by RoderickQiu** [comment]
![image.png](https://i.loli.net/2020/04/17/i4su27Nd8ThBt1J.png)

这张如何。
