### ISSUE TITLE
new feature: bedtime/downtime mode 😜

### ISSUE THREAD

**Issue by boykensoidong** [RoderickQiu/wnr#90]
I had a great time using the WNR focus/promodo app. with 25work-5mins rule.
 
thanks Roderick Qiu very much for help other people has better/healthy life 🥰

Working on laptop has a lot of interesting things to do, so i can't force myself go to bed earlier. 1-2AM working late
 lack of sleep actually damaged to my brain, mental health.

I tried to duplicate WNR on macos app. but it uses/saves the same data. so i can't use it as 2 standalone apps. with 2 purposes:
1 -for focus-relax,
2 -for bedtime mode

so could you make a (bedtime/downtime mode) intergrate into WN R app? or make a different app with the same sourceCode to resolve my problem/bad habits. and make WNR the most wellbeing and strict app ever.

My idea about bedtime mode is:
(Ability for setting a specific time at custom time, example 10PM). the app will automatically start a Rest from 30-mins to -> 2hours or couples of hours). can't use laptop at 10PM and a few hours after that. so we tend to go to bed earlier.

I'm excited for the next update feature of wrn. 😭  that I mentioned above. thank you very much 🥺 hope you make it soon

**Comment by RoderickQiu** [comment]
Good suggestion. Will try to make it later.

**Comment by boykensoidong** [comment]
Hopefully it will be easy to get things done,  worth waiting!

**Comment by RoderickQiu** [comment]
Didn't seem to have a lot of time, so the bedtime mode will be made later. Before that's done, you can check out this: https://github.com/RoderickQiu/wnr/releases/tag/v1.28.1-2nd which is the mode I just made as a second instance of wnr.

**Comment by boykensoidong** [comment]
nice, i used Wnr-2nd for playing around in-app setting, beside the main WNR 2.8.1. 

After looking closely in setting, _I see the feature of [Task-Reservation ] "Preplan a task for the future" is exactly the same bedtime mode that i wishing for._ 

i gernerally preset 2 tasks: 
1-exercise time (good)
2-bedtime (the most important)

_but in the early stage it's not stable enough._

**Comment by boykensoidong** [comment]
by the way: 
i use this trick for bedtime mode 99% work
**but it has cons:**
- mannualy click start timing, then quit app everyday. 😭

-------
like this video i have recorded here:
https://youtu.be/th3vaXeD_BM
1. Start timing then **QUIT** app.
2. use Calendar to schedule **OPEN** wnr at 10:00pm, **(will continues re-counting from 1 above)**
3. quit wnr app at 5:00am (before using laptop at morning) Via Automator (exit app purpose)

hope you make it stable! ❤️

**Comment by RoderickQiu** [comment]
Being busy again lately, but your ideas are great. Will consider later.

**Comment by RoderickQiu** [comment]
> by the way: i use this trick for bedtime mode 99% work **but it has cons:**
> 
>     * mannualy click start timing, then quit app everyday. 😭
> 
> 
> like this video i have recorded here: https://youtu.be/th3vaXeD_BM
> 
>     1. Start timing then **QUIT** app.
> 
>     2. use Calendar to schedule **OPEN** wnr at 10:00pm, **(will continues re-counting from 1 above)**
> 
>     3. quit wnr app at 5:00am (before using laptop at morning) Via Automator (exit app purpose)
> 
> 
> hope you make it stable! ❤️

Oh anyway, if you manage to auto-start it everyday, then you can try the setting that let the default preset be started automatically - and choose fullscreen mode on. Does that help?

**Comment by boykensoidong** [comment]
> 

no, i found in wnr setting there is no way to set (default preset be started automatically) when launch the app. consider to make ability to start-timing automatically on default preset , right after user open app. make a check box or run as default 
like this 😀
![Uploading Screenshot 2023-02-21 at 00.19.21.png…]()

**Comment by RoderickQiu** [comment]
Oh I thought I've made that feature but actually I didn't qwq... Will make this in next version.

**Comment by RoderickQiu** [comment]
Just found that I've truly made that before but got that setting section missing when I refactored the preferences panel. So I quickly come up with this function. Anyway, because I'm lazy about making a new version about simply this change, tell me the platform you use (win-installer, win-zip, mac) and your preferred arch and I'll send you a version separately.

**Comment by boykensoidong** [comment]
okay, i understand! 
i mainly use Macos, rarely work on Winx64 .you could put it over github or send me to mail boykensoidong@gmail.com thanks! 
my Primary mail (tuantran93hb@gmail.com) is out of 16gb free storage

**Comment by RoderickQiu** [comment]
Posted on https://www.mediafire.com/file/npnu01utjg4fmmr/wnr-2nd-1.28plus.zip/file

**Comment by boykensoidong** [comment]
Awsome, you're thougtful!
Thank again for making this the earlier version come up with auto start-timing. i was using wnr-2nd for downtime (bed/excercise time) and it really worked 😀 100% 

With some steps set up: 
Macos: (Automator + calendar) 
https://allthings.how/how-to-automatically-launch-and-close-an-app-on-mac-at-scheduled-times/
Windows: (Task schedule)
https://www.makeuseof.com/tag/how-to-automate-windows-programs-on-a-schedule/#:~:text=To%20schedule%20an%20automatic%20task,Library%2C%20and%20select%20New%20Folder%E2%80%A6
https://www.conceptworld.com/blog/index.php/run-an-app-automatically-at-specific-time-using-a-windows-task-scheduler-alternative/

**Comment by boykensoidong** [comment]
one more feature's suggestion maybe useful too. 

<img width="298" alt="Screenshot 2023-03-08 at 18 46 45" src="https://user-images.githubusercontent.com/83786393/223708807-b2cfd82c-5bd4-4d89-9c59-a396ab5eb8c6.png">

**Pause when computer is on system idle** _("The computer is considered to be idle by Windows if there has not been user interaction via the mouse or keyboard for a given time " )_

Describe bellow:

**1. Non-fullscreen** (user is working on PC, by some reasons they leave PC for 5mins,10mins,15mins... And back to work) so we need Idle tracking mouse here
_I mean: pause when no mouse is moving in about 3mins, continue counting when user back to work._ 

**2. Fullscreen-counting** ( **ignore IDLE tracking at this sceen** because In this case: user relax and stay away from PC, so require time continue counting to end to complete session)

**Comment by boykensoidong** [comment]
watch video see how it works:
https://youtube.com/shorts/vqY7aDw3RX0?feature=share

similar apps has that feature: 
Tadama Workflow-Timer (Auto start and IDLE)
https://github.com/boykensoidong/FOCUS_BREAK_Timer_APP--Tadama-Workflow-Timer--Pavel-Alexeev

**Comment by RoderickQiu** [comment]
Another guy asked me this the other day, but I might not add it because I think in every this kind of case you can manually stop your task. But this do remind me, that I shall really make something, that, if it has been paused for long, allow the people to restart this period to start counting down again. Let's see when I will be free to do this because I will be likely to have some big tasks recently.

**Comment by boykensoidong** [comment]
ok fine. Idle is not necessary to me, next time i use the hotkey to pause quickly 😋

_a little acceptable bug i found today, tell you know why 
"auto start default task" does not run when any "task reservasion" is added.  https://youtu.be/iTLzTTzL3iI_

**Comment by boykensoidong** [comment]
> Posted on https://www.mediafire.com/file/npnu01utjg4fmmr/wnr-2nd-1.28plus.zip/file

By the way, do you still keep wnr-2nd version from your pc?

sorry for bother you, but today **i realize that it's indeed slowly** when run on **Mac M1 Chipset** with WNR **-2ND** MacOS-x64 compared to ARM64 native-version. you can see how slowly it was in video: https://youtube.com/playlist?list=PLlC3TpmfvbrB05omCbxeZNu2ZR_Aupaiv

**wnr-2nd-1.28plus** you had exported only 64bit (not Arm64). it was my fault not telling you exactly my M1-ARM cpu.

could you re-build/export wnr-2ND ARM64 for me 🥺
u could manually edit and add new update item on github web release page (pre-realease of 2nd ver)
https://github.com/RoderickQiu/wnr/releases/tag/v1.28.1-2nd
I will check 2nd release page later by myself! thanks
<img width="860" alt="Screenshot 2023-03-10 at 15 51 48" src="https://user-images.githubusercontent.com/83786393/224273530-a118ee1a-23e1-4724-9724-c8b660fb0bc2.png">

**Comment by RoderickQiu** [comment]
<img width="916" alt="截屏2023-03-10 22 56 31" src="https://user-images.githubusercontent.com/42290260/224348390-5151776e-dc27-40a5-890a-765177311de1.png">
There's already an ARM build for macOS here, in the assets section of https://github.com/RoderickQiu/wnr/releases/tag/v1.28.1-2nd , isn't this what you are seeking anyway

**Comment by RoderickQiu** [comment]
> ok fine. Idle is not necessary to me, next time i use the hotkey to pause quickly 😋
> 
> _a little acceptable bug i found today, tell you know why "auto start default task" does not run when any "task reservasion" is added. https://youtu.be/iTLzTTzL3iI_

Yes, just found that bug, and will be merged in next version, thanks.

**Comment by boykensoidong** [comment]
not yet
> Posted on https://www.mediafire.com/file/npnu01utjg4fmmr/wnr-2nd-1.28plus.zip/file
<img width="843" alt="Screenshot 2023-03-11 at 05 37 51" src="https://user-images.githubusercontent.com/83786393/224441619-3fad803d-836e-43f0-87d3-8e57836f875c.png">
<img width="1009" alt="Screenshot 2023-03-11 at 05 42 34" src="https://user-images.githubusercontent.com/83786393/224442037-f0c5b404-0f3f-4e6c-981f-ac63ee43d455.png">
wnr-2nd-1.28plus.zip i had download not include Arm ver 
wnr-2nd-1.28plus.zip & wnr-2nd-1.29 has (**auto start default task**, old ver wnr-2nd-1.28 haven't has) i use for bedtime mode  when "Task reservation" is not stable enough

**Comment by RoderickQiu** [comment]
https://github.com/RoderickQiu/wnr/releases/download/v1.28.1-2nd/wnr-2nd-1.28.1-2nd-MacOS-x64-PLUS.dmg

**Comment by boykensoidong** [comment]
Oh-damn! A little confused 🤣 
I'm using MacBook M1 **ARM** chipset, **not intel** cpu
<img width="549" alt="Screenshot 2023-03-12 at 11 20 52" src="https://user-images.githubusercontent.com/83786393/224524775-cd2d2082-2d1e-4e5a-9ab7-4f82a58e59b7.png">
Hope you find passion in your work and peace in your workplace. Have a nice day ahead!

**Comment by RoderickQiu** [comment]
Oh ah, sorry. Mistakenly uploaded wrong file.
https://github.com/RoderickQiu/wnr/releases/download/v1.28.1-2nd/wnr-2nd-1.28.1plus-2nd-MacOS-arm64.dmg

**Comment by boykensoidong** [comment]
Enjoy that much. Thanks RoderickQiu!
_This ver also fixed bug: auto start-timing when any task reservation is added._
