### ISSUE TITLE
功能建议：关闭交互

### ISSUE THREAD

**Issue by Wang-Alan** [RoderickQiu/wnr#91]
建议点击右上角的关闭按钮之后，弹出框除了「确认」和「取消」外，可以增加「mini模式」和「隐藏至托盘菜单」
![image](https://user-images.githubusercontent.com/16968055/222883454-51c46a06-4310-44f0-86c3-59d21836f0e7.png)

**Comment by RoderickQiu** [comment]
确实有很多的软件是这么设置的，但既然长期以来没用这么设置，暂时也懒得改了。你如果觉得有必要，可以开pullrequest。
