### ISSUE TITLE
最后一分钟可以显示为秒

### ISSUE THREAD

**Issue by xiaoxin6182** [RoderickQiu/wnr#92]
建议在设置里面增加一个选项，可以在最后一分钟显示为秒（MINI模式时），如下图
![Snipaste_2023-03-07_09-52-31](https://user-images.githubusercontent.com/115337904/223298780-61341d91-3818-4a0a-b53e-f1086333d6d7.png)

**Comment by boykensoidong** [comment]
<img width="592" alt="Screenshot 2023-03-08 at 17 19 40" src="https://user-images.githubusercontent.com/83786393/223691000-70f75aaf-e108-4419-9e9a-c2fcc77ecbc6.png">

**Comment by RoderickQiu** [comment]
> 建议在设置里面增加一个选项，可以在最后一分钟显示为秒（MINI模式时），如下图 ![Snipaste_2023-03-07_09-52-31](https://user-images.githubusercontent.com/115337904/223298780-61341d91-3818-4a0a-b53e-f1086333d6d7.png)

合理的，我直接把默认的这么改过去好了。

**Comment by RoderickQiu** [comment]
> <img alt="Screenshot 2023-03-08 at 17 19 40" width="592" src="https://user-images.githubusercontent.com/83786393/223691000-70f75aaf-e108-4419-9e9a-c2fcc77ecbc6.png">

OK, will try fix this in next version.

**Comment by RoderickQiu** [comment]
All done, will be published next version.
