### ISSUE TITLE
请问每次工作时间结束，提示休息时，和休息结束，切回工作时，那个提示确认框怎么取消掉？

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [RoderickQiu/wnr#93]
另外这软件设置够复杂的。

**Comment by RoderickQiu** [comment]
<img width="364" alt="截屏2023-03-09 22 33 25" src="https://user-images.githubusercontent.com/42290260/224056927-0c301665-aa81-4926-8c3c-4a52877bbee7.png">
这软件刚开始开发时候，我还从未学过任何的项目管理理论，说实在，我自己也没想到能做这么久，做这么多功能。某种意义上，这也就是个祖传屎坑了，那么功能越加越多就难免复杂。受不了就不用呗。
