### ISSUE TITLE
MNI模式BUG

### ISSUE THREAD

**Issue by Likboc** [RoderickQiu/wnr#98]
番茄计时法，工作时间倒计时最后一分钟会卡时间，计时停止。
点击“暂时/停止”按钮重新计时后恢复正常。
![T8D~$7Y84PYUG02Z@F@%`9O](https://user-images.githubusercontent.com/73859384/228506626-22ca527c-eb86-450d-88ab-81da5046db62.png)
@RoderickQiu

**Comment by RoderickQiu** [comment]
抱歉前段时间忘了回复。但我在mac和win11上都没能复现？你使用的wnr版本？有视频记录吗？

**Comment by Likboc** [comment]
使用的是WIN11 X64版本，最后2分钟视频。
https://user-images.githubusercontent.com/73859384/229518502-7de329b8-0d8b-4ed3-bab2-80638e585bb0.mp4

**Comment by RoderickQiu** [comment]
不好意思，我真做不到，不知道你怎么实现的。
在我这里，无论怎么搞都是59、58、57秒这样倒数的。
有更多信息可以再找我。

**Comment by Likboc** [comment]
好吧 感谢你的恢复
